// 30+ additional programmatic SEO openings. Pure long-tail capture for Google.
// These have NO matching OPENINGS_DATABASE entry — landing renders from STANDALONE fields below.
// All entries: real openings, real ECO codes, real strategic ideas. No filler content.

import type { OpeningSeoMeta } from "./opening-seo-meta";

type ExtraEntry = OpeningSeoMeta & {
  name: string;
  eco: string;
  category: string;
  difficulty: string;
  startingMoves: string;
  description: string;
};

export const EXTRA_OPENINGS: Record<string, ExtraEntry> = {
  "sicilian-najdorf": {
    id: "sicilian-najdorf", slug: "sicilian-najdorf", searchVolume: 14800,
    name: "Sicilian Najdorf", eco: "B90–B99", category: "sicilian", difficulty: "advanced",
    startingMoves: "1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6",
    description: "The fiercest Sicilian — Fischer and Kasparov's main weapon. ...a6 prepares ...e5/...b5 expansion.",
    longTitle: "Sicilian Najdorf — Fischer's Killer Weapon",
    longDescription: "Sicilian Najdorf (5...a6) — the sharpest 1.e4 reply. English Attack, Poisoned Pawn, 6.Be2 lines explained.",
    keyIdeas: ["Use ...a6 to prepare ...b5 and ...Bb7", "Hit back with ...e5 to grab the d5 outpost", "Counter the English Attack (6.Be3) with ...e5 + ...Be6", "In the Poisoned Pawn (6.Bg5 e6 7.f4 Qb6) — accept and weather the storm"],
    famousGames: ["Fischer vs Spassky 1972 Game 6", "Kasparov vs Topalov 1999 — the Immortal"],
    faqs: [
      { q: "Why is the Najdorf so popular?", a: "It's flexible, theoretically rich, and creates the most asymmetric positions of any defense to 1.e4." },
      { q: "Is the Najdorf hard to learn?", a: "Yes — extremely theory-heavy. Beginners should start with simpler Sicilians like the Kan or Taimanov." },
    ],
  },
  "sicilian-dragon": {
    id: "sicilian-dragon", slug: "sicilian-dragon", searchVolume: 9900,
    name: "Sicilian Dragon", eco: "B70–B79", category: "sicilian", difficulty: "advanced",
    startingMoves: "1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 g6",
    description: "Fianchetto the bishop on g7 and aim every piece at the Yugoslav Attack king-hunt.",
    longTitle: "Sicilian Dragon — Yugoslav Attack & Theory",
    longDescription: "Sicilian Dragon (5...g6) — fianchetto bishop, opposite-side castling, both kings under fire from move 1.",
    keyIdeas: ["Fianchetto the bishop to g7 — long-diagonal pressure", "Race White on the queenside attack", "Trade the dark-squared bishops with ...Bxc3", "Open the c-file with ...Rc8 + ...Rxc3"],
    famousGames: ["Karpov vs Korchnoi 1974 — main-line Yugoslav", "Carlsen vs Radjabov 2012"],
    faqs: [
      { q: "Is the Dragon still playable?", a: "Yes — Magnus Carlsen and Anish Giri still use it. Theory is dense but the lines are forced and learnable." },
      { q: "Dragon vs Najdorf?", a: "Dragon is more thematic (race attack); Najdorf is more flexible and strategic." },
    ],
  },
  "sicilian-sveshnikov": {
    id: "sicilian-sveshnikov", slug: "sicilian-sveshnikov", searchVolume: 5400,
    name: "Sicilian Sveshnikov", eco: "B33", category: "sicilian", difficulty: "advanced",
    startingMoves: "1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 e5",
    description: "Magnus Carlsen's pet line — accept the d5 hole for dynamic piece play.",
    longTitle: "Sicilian Sveshnikov — Carlsen's Choice",
    longDescription: "Sveshnikov (5...e5) — the modern Sicilian. Theoretical workhorse Carlsen used vs Caruana 2018.",
    keyIdeas: ["Accept the d5 weakness for piece activity", "Use ...f5 to challenge the e4 pawn", "Maneuver the b6 knight via b8-d7", "Aim for the bishop pair on long diagonals"],
    famousGames: ["Carlsen vs Caruana 2018 WCC Game 6", "Kramnik vs Leko 2004"],
    faqs: [
      { q: "Why did Carlsen choose Sveshnikov vs Caruana?", a: "Solid yet dynamic — gives Black real winning chances without theoretical risk." },
      { q: "Sveshnikov main line?", a: "6.Ndb5 d6 7.Bg5 a6 8.Na3 b5 — leads to deeply analyzed sharp positions." },
    ],
  },
  "sicilian-accelerated-dragon": {
    id: "sicilian-accelerated-dragon", slug: "sicilian-accelerated-dragon", searchVolume: 2900,
    name: "Accelerated Dragon", eco: "B34–B39", category: "sicilian", difficulty: "intermediate",
    startingMoves: "1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 g6",
    description: "Fianchetto without committing ...d6 — sidesteps the Yugoslav Attack but invites the Maróczy Bind.",
    longTitle: "Accelerated Dragon — Sidestep the Yugoslav",
    longDescription: "Accelerated Dragon (4...g6) — quick fianchetto avoiding the Yugoslav Attack, accepting the Maróczy.",
    keyIdeas: ["Skip ...d6 to sidestep the Yugoslav Attack", "Counter the Maróczy Bind with ...d6 + ...a5", "Use ...Nxd4 followed by ...Bg7", "Prepare ...b5 to break the Maróczy clamp"],
    faqs: [
      { q: "Accelerated vs regular Dragon?", a: "Avoids 9.Bc4 lines but allows the Maróczy Bind (5.c4) which restricts Black's space." },
      { q: "How to handle the Maróczy?", a: "Patient piece play, ...Nxd4, ...Bg7, then ...a5 / ...b5 break — long strategic battle." },
    ],
  },
  "kid-mar-del-plata": {
    id: "kid-mar-del-plata", slug: "kings-indian-mar-del-plata", searchVolume: 880,
    name: "King's Indian — Mar del Plata", eco: "E97–E99", category: "indian defense", difficulty: "advanced",
    startingMoves: "1.d4 Nf6 2.c4 g6 3.Nc3 Bg7 4.e4 d6 5.Nf3 O-O 6.Be2 e5 7.O-O Nc6 8.d5 Ne7",
    description: "The most thematic King's Indian — Black storms the kingside, White the queenside. Pure race chess.",
    longTitle: "Mar del Plata Variation — KID Race Attack",
    longDescription: "King's Indian Mar del Plata (E97–E99) — symmetrical race: Black plays ...f5/...g4/...g3, White hits with c5/b4.",
    keyIdeas: ["Lock the center with d5 vs ...Ne7", "Race kingside with ...f5, ...g4, ...g3", "Sacrifice on the kingside (Nh5, Nf4) for direct mate", "Trade the dark-squared bishop only when timing is perfect"],
    famousGames: ["Kasparov vs Karpov 1990 — model attack", "Nakamura vs Aronian 2011"],
    faqs: [
      { q: "Is the Mar del Plata still played?", a: "Yes — Nakamura keeps it alive. Theory is sharp but ideas matter more than memorization." },
      { q: "Best White antidote?", a: "9.b4 (Bayonet Attack) is the modern try — fast queenside expansion before Black's kingside lands." },
    ],
  },
  "grunfeld-defense": {
    id: "grunfeld-defense", slug: "grunfeld-defense", searchVolume: 5400,
    name: "Grünfeld Defense", eco: "D70–D99", category: "indian defense", difficulty: "advanced",
    startingMoves: "1.d4 Nf6 2.c4 g6 3.Nc3 d5",
    description: "Hypermodern challenge — let White build a big center then attack it from the wings.",
    longTitle: "Grünfeld Defense — Hypermodern Counter-Attack",
    longDescription: "Grünfeld Defense (1.d4 Nf6 2.c4 g6 3.Nc3 d5) — Kasparov's & Svidler's main weapon vs 1.d4.",
    keyIdeas: ["Trade ...d5 for the center, then dismantle it", "Pressure d4 with ...c5 and ...Bg7", "Use the long diagonal for the fianchetto bishop", "Counter Exchange Variations (4.cxd5) with ...Nxd5 + ...c5"],
    famousGames: ["Kasparov vs Karpov 1990 WCC Game 19", "Svidler vs Aronian 2014"],
    faqs: [
      { q: "Grünfeld vs King's Indian?", a: "Grünfeld attacks the center directly; KID lets it stand and counter-attacks the king." },
      { q: "Is the Grünfeld theoretical?", a: "Very — but ideas (long diagonal, ...c5 break, ...Qa5 pressure) recur in every line." },
    ],
  },
  "benoni-defense": {
    id: "benoni-defense", slug: "benoni-defense", searchVolume: 4400,
    name: "Modern Benoni", eco: "A60–A79", category: "indian defense", difficulty: "advanced",
    startingMoves: "1.d4 Nf6 2.c4 c5 3.d5 e6",
    description: "Asymmetric double-edged structure — Black's queenside majority vs White's central pawns.",
    longTitle: "Modern Benoni — Tal's Aggressive Choice",
    longDescription: "Modern Benoni (1.d4 Nf6 2.c4 c5 3.d5 e6) — sharp, dynamic, played by Tal and Topalov.",
    keyIdeas: ["Use the queenside pawn majority for ...b5 break", "Activate the dark-squared bishop on g7", "Counter the Taimanov Attack (8.Bb5+) with ...Nfd7", "Aim for ...f5 in classical lines"],
    famousGames: ["Tal vs Larsen 1965 — kingside masterpiece", "Topalov vs Kramnik 1999"],
    faqs: [
      { q: "Is the Benoni risky?", a: "Yes — White gets space and easy development. Black plays for sharp imbalances." },
      { q: "Modern Benoni vs Benko Gambit?", a: "Benoni keeps pawns; Benko sacrifices a pawn for queenside files and pressure." },
    ],
  },
  "benko-gambit": {
    id: "benko-gambit", slug: "benko-gambit", searchVolume: 3600,
    name: "Benko Gambit", eco: "A57–A59", category: "indian defense", difficulty: "intermediate",
    startingMoves: "1.d4 Nf6 2.c4 c5 3.d5 b5",
    description: "Sacrifice the b-pawn for permanent queenside pressure — one of chess's soundest gambits.",
    longTitle: "Benko Gambit — Sound Pawn Sacrifice",
    longDescription: "Benko Gambit (1.d4 Nf6 2.c4 c5 3.d5 b5) — sacrifice for permanent queenside file pressure.",
    keyIdeas: ["Sacrifice the b-pawn for the a- and b-files", "Fianchetto the bishop to g7 for endgame power", "Use the queenside files even after queens trade", "Endgames favor Black thanks to active rooks"],
    faqs: [
      { q: "Is the Benko sound?", a: "Yes — Black's compensation is structural and lasts into the endgame. White's extra pawn is hard to use." },
      { q: "Best refutation?", a: "Modern theory likes 4.Nf3 (Half-Accepted) or 4.Qc2 to keep the pawn without exchanges." },
    ],
  },
  "dutch-defense": {
    id: "dutch-defense", slug: "dutch-defense", searchVolume: 5400,
    name: "Dutch Defense", eco: "A80–A99", category: "queen's pawn", difficulty: "intermediate",
    startingMoves: "1.d4 f5",
    description: "Stake out kingside space and aim every piece at the White king. Stonewall, Leningrad, Classical.",
    longTitle: "Dutch Defense — Stonewall, Leningrad & Classical",
    longDescription: "Dutch Defense (1.d4 f5) — kingside attack from move 1. Pick from Stonewall, Leningrad, or Classical setups.",
    keyIdeas: ["Stonewall: pawns on c6/d5/e6/f5 — fortress + kingside attack", "Leningrad: ...g6 / ...Bg7 — King's Indian feel vs 1.d4", "Classical: ...e6/...d6 + queenside dev", "Aim for ...Ne4 outpost and ...Qe8-h5 attack"],
    faqs: [
      { q: "Is the Dutch risky?", a: "1...f5 weakens the e6 square but gains kingside space. Strong if you handle the king carefully." },
      { q: "Best Dutch line for beginners?", a: "Stonewall — locks the structure and gives a clear attacking plan with ...Ne4 and ...Qh5." },
    ],
  },
  "trompowsky-attack": {
    id: "trompowsky-attack", slug: "trompowsky-attack", searchVolume: 4400,
    name: "Trompowsky Attack", eco: "A45", category: "queen's pawn", difficulty: "intermediate",
    startingMoves: "1.d4 Nf6 2.Bg5",
    description: "Sidestep mainstream theory — pin the knight on move 2 and aim for offbeat structures.",
    longTitle: "Trompowsky Attack — Anti-Theory 1.d4",
    longDescription: "Trompowsky (1.d4 Nf6 2.Bg5) — surprise weapon avoiding KID, Grünfeld, Nimzo theory altogether.",
    keyIdeas: ["Pin the f6 knight, force ...Ne4 or doubled pawns", "Aim for an early c4 push to grab space", "Trade off your bishop for structural concessions", "Steer into less-analyzed middlegames"],
    faqs: [
      { q: "Is the Trompowsky sound?", a: "Yes — Hodgson and Carlsen both used it at top level. Sound enough, surprise value high." },
      { q: "Trompowsky vs London System?", a: "Tromp is more ambitious and sharper; London is calmer and easier to play with both colors." },
    ],
  },
  "catalan-opening": {
    id: "catalan-opening", slug: "catalan-opening", searchVolume: 5400,
    name: "Catalan Opening", eco: "E01–E09", category: "queen's pawn", difficulty: "advanced",
    startingMoves: "1.d4 Nf6 2.c4 e6 3.g3",
    description: "Fianchetto + queen's pawn — the strongest positional weapon of the modern era. Kramnik's pet.",
    longTitle: "Catalan Opening — Kramnik's Power Weapon",
    longDescription: "Catalan (1.d4 Nf6 2.c4 e6 3.g3) — fianchetto + queen's pawn = one of the deadliest positional openings.",
    keyIdeas: ["Long-diagonal bishop creates permanent pressure on c6/d5", "Use ...dxc4 lines to recover the pawn cleanly", "Aim for the d5 break in the Open Catalan", "Endgames favor White thanks to the bishop's range"],
    famousGames: ["Kramnik vs Topalov 2006 WCC", "Carlsen vs Anand 2013 WCC Game 5"],
    faqs: [
      { q: "Is the Catalan hard to learn?", a: "Easier than the Najdorf — the bishop's diagonal does the work. Plans recur across all variations." },
      { q: "Best Black response?", a: "Open Catalan (...dxc4) is principled; Closed Catalan (...c6) is solid and avoids forced lines." },
    ],
  },
  "bishops-opening": {
    id: "bishops-opening", slug: "bishops-opening", searchVolume: 1900,
    name: "Bishop's Opening", eco: "C23–C24", category: "open game", difficulty: "beginner",
    startingMoves: "1.e4 e5 2.Bc4",
    description: "Aim the bishop at f7 immediately — a cousin of the Italian that often transposes.",
    longTitle: "Bishop's Opening — Easy 1.e4 Weapon",
    longDescription: "Bishop's Opening (1.e4 e5 2.Bc4) — point at f7 from move 2, sidestep Petroff, transpose at will.",
    keyIdeas: ["Aim the bishop at the f7 square immediately", "Sidestep the Petroff and Berlin Wall", "Transpose to Italian or Vienna at will", "Use d3 + Nf3 for solid, classical development"],
    faqs: [
      { q: "Bishop's Opening vs Italian Game?", a: "Bishop's plays Bc4 first, keeping the f3 knight flexible — often transposes to Italian anyway." },
      { q: "Is it good for club play?", a: "Excellent — easy to learn, dodges Petroff theory, leads to classical attacks." },
    ],
  },
  "scotch-game": {
    id: "scotch-game", slug: "scotch-game", searchVolume: 6600,
    name: "Scotch Game", eco: "C44–C45", category: "open game", difficulty: "intermediate",
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.d4",
    description: "Open the center on move 3 — Garry Kasparov's revival weapon vs the Berlin Wall.",
    longTitle: "Scotch Game — Kasparov's Revival",
    longDescription: "Scotch Game (1.e4 e5 2.Nf3 Nc6 3.d4) — open the center, sidestep the Ruy Lopez Berlin, attack early.",
    keyIdeas: ["Open the center with d4 on move 3", "Aim for quick development and central pressure", "Use the Mieses (4...Nf6 5.Nxc6 bxc6 6.e5) line for sharp positions", "Sidestep the Berlin Wall headache"],
    famousGames: ["Kasparov vs Karpov 1990 — Scotch Mieses", "Carlsen vs Caruana 2018"],
    faqs: [
      { q: "Why did Kasparov play the Scotch?", a: "To dodge Karpov's deep Spanish prep — same idea Carlsen later used vs Caruana." },
      { q: "Is the Scotch easy?", a: "Easier than the Ruy Lopez. Less theory, sharper play, clear plans." },
    ],
  },
  "evans-gambit": {
    id: "evans-gambit", slug: "evans-gambit", searchVolume: 2400,
    name: "Evans Gambit", eco: "C51–C52", category: "open game", difficulty: "intermediate",
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.b4",
    description: "19th-century romantic gambit revived by Kasparov — sacrifice the b-pawn for a roaring center.",
    longTitle: "Evans Gambit — Romantic Pawn Sacrifice",
    longDescription: "Evans Gambit (4.b4) — Kasparov revived this 19th-century weapon to crush Anand. Pure attacking chess.",
    keyIdeas: ["Sacrifice b4 to gain c3 + d4 center", "Aim Bxf7+ ideas at the exposed Black king", "Use the open b-file for queenside pressure", "Convert development into a direct mating attack"],
    faqs: [
      { q: "Is the Evans Gambit sound?", a: "Mostly — Black has equalizing methods (5...Bxb4 6.c3 Be7 / Ba5), but practical results favor White at club level." },
      { q: "How did Kasparov use it?", a: "Crushed Anand 1995 — the game made every modern attacker reconsider 19th-century gambits." },
    ],
  },
  "queens-gambit-accepted": {
    id: "queens-gambit-accepted", slug: "queens-gambit-accepted", searchVolume: 6600,
    name: "Queen's Gambit Accepted", eco: "D20–D29", category: "queen's pawn", difficulty: "intermediate",
    startingMoves: "1.d4 d5 2.c4 dxc4",
    description: "Take the pawn, free the bishop, and hold the c4 square. Practical and theoretically solid.",
    longTitle: "Queen's Gambit Accepted — QGA Theory",
    longDescription: "Queen's Gambit Accepted (1.d4 d5 2.c4 dxc4) — practical, principled, easier than QGD.",
    keyIdeas: ["Capture cxc4 to free the c8-bishop", "Counter e4 push with ...e6 + ...c5 break", "Don't try to hold c4 — let it go and develop", "Use ...a6 to support ...b5 expansion"],
    faqs: [
      { q: "QGA vs QGD?", a: "QGA frees the c8-bishop early and is more dynamic; QGD is solider but locks the bishop in." },
      { q: "Best QGA line for beginners?", a: "Classical 3.Nf3 Nf6 4.e3 e6 — simple development, clear plans." },
    ],
  },
  "semi-slav-defense": {
    id: "semi-slav-defense", slug: "semi-slav-defense", searchVolume: 2400,
    name: "Semi-Slav Defense", eco: "D43–D49", category: "queen's pawn", difficulty: "advanced",
    startingMoves: "1.d4 d5 2.c4 c6 3.Nc3 Nf6 4.Nf3 e6",
    description: "Combine Slav solidity with QGD flexibility — the Meran and Botvinnik are razor-sharp.",
    longTitle: "Semi-Slav Defense — Meran & Botvinnik Lines",
    longDescription: "Semi-Slav (1.d4 d5 2.c4 c6 3.Nc3 Nf6 4.Nf3 e6) — Slav solidity + QGD flexibility, with sharp Meran lines.",
    keyIdeas: ["Combine Slav (...c6) and QGD (...e6) ideas", "Aim for ...dxc4 + ...b5 with the Meran", "Use Botvinnik (5...dxc4 6.Bxc4 Bb4) for sharp tactics", "Counter Anti-Meran with ...h6 + ...Bb4"],
    famousGames: ["Anand vs Kramnik 2008 WCC Game 5", "Topalov vs Kramnik 2006 WCC"],
    faqs: [
      { q: "Semi-Slav vs Slav?", a: "Semi-Slav allows ...Bg5 pin (Bf4 lines); Slav keeps the bishop active outside the chain." },
      { q: "Is Botvinnik still playable?", a: "Yes but ferociously theoretical. The Meran is more practical for everyday play." },
    ],
  },
  "queens-gambit-declined": {
    id: "queens-gambit-declined", slug: "queens-gambit-declined", searchVolume: 9900,
    name: "Queen's Gambit Declined", eco: "D30–D69", category: "queen's pawn", difficulty: "intermediate",
    startingMoves: "1.d4 d5 2.c4 e6",
    description: "The most respected defense to 1.d4 — every World Champion has played it.",
    longTitle: "Queen's Gambit Declined — QGD Main Lines",
    longDescription: "Queen's Gambit Declined (1.d4 d5 2.c4 e6) — Capablanca's, Karpov's, and Anand's classical defense.",
    keyIdeas: ["Defend d5 with ...e6 — keeps the structure solid", "Develop the c8-bishop via ...b6 + ...Bb7 (Tartakower)", "Use the Lasker freeing maneuver (...Ne4 trade)", "Counter the Exchange Variation with ...c6 + ...Re8"],
    famousGames: ["Capablanca vs Lasker 1921 WCC", "Karpov vs Kasparov 1985 WCC Game 16"],
    faqs: [
      { q: "QGD vs Slav?", a: "QGD locks the c8-bishop in but is more flexible elsewhere; Slav frees the bishop but commits the c-pawn." },
      { q: "Is QGD too passive?", a: "Far from it — the Tartakower and Lasker variations give Black active play and equalization." },
    ],
  },
  "petrov-defense": {
    id: "petrov-defense", slug: "petrov-defense", searchVolume: 4400,
    name: "Petrov Defense", eco: "C42–C43", category: "open game", difficulty: "intermediate",
    startingMoves: "1.e4 e5 2.Nf3 Nf6",
    description: "Symmetric, solid, drawish reputation — Karpov's secret weapon for Black draws with White.",
    longTitle: "Petrov Defense — Russian Defense (Solid)",
    longDescription: "Petrov Defense (1.e4 e5 2.Nf3 Nf6) — solid, symmetric, the safest Black answer to 1.e4.",
    keyIdeas: ["Mirror White's setup symmetrically", "Use the Classical (3.Nxe5 d6 4.Nf3 Nxe4) for active piece play", "Counter Cochrane Gambit (4.Nxf7) with ...Kxf7 + ...c5", "Aim for endgame equality with simplifications"],
    faqs: [
      { q: "Why is the Petrov drawish?", a: "Symmetry minimizes risk. But sharp attempts (Cochrane Gambit, 5.Nc3) keep it interesting." },
      { q: "Is the Petrov boring?", a: "At top level, often. At club level, one tactical mistake can decide the game in a flash." },
    ],
  },
  "ponziani-opening": {
    id: "ponziani-opening", slug: "ponziani-opening", searchVolume: 1600,
    name: "Ponziani Opening", eco: "C44", category: "open game", difficulty: "beginner",
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.c3",
    description: "Old-school surprise weapon — prepare d4 with c3 instead of going Italian or Spanish.",
    longTitle: "Ponziani Opening — Old-School Surprise",
    longDescription: "Ponziani Opening (1.e4 e5 2.Nf3 Nc6 3.c3) — surprise weapon that builds the center with c3 + d4.",
    keyIdeas: ["Support d4 with c3 first", "Sidestep Berlin and Petroff theory", "Aim for a quick d4 + Bg5 setup", "Use Réti Variation (3...Nf6 4.d4) for active play"],
    faqs: [
      { q: "Is the Ponziani sound?", a: "Sound but limited — Black equalizes with 3...d5 (Jaenisch) or 3...Nf6 (Réti)." },
      { q: "Why play the Ponziani?", a: "Surprise factor — most opponents have no theory beyond move 4." },
    ],
  },
  "colle-system": {
    id: "colle-system", slug: "colle-system", searchVolume: 2900,
    name: "Colle System", eco: "D04–D05", category: "queen's pawn", difficulty: "beginner",
    startingMoves: "1.d4 d5 2.Nf3 Nf6 3.e3",
    description: "Easy 1.d4 setup — c3, Bd3, e3-e4 break. Perfect for learning d-pawn principles.",
    longTitle: "Colle System — Easy 1.d4 for Beginners",
    longDescription: "Colle System (1.d4 d5 2.Nf3 Nf6 3.e3) — easy setup with c3, Bd3, e4 break. Ideal beginner weapon.",
    keyIdeas: ["Build a solid pyramid: d4-e3-c3", "Aim for the e4 break to open lines", "Use Bd3 to point at h7", "Castle short, then attack with Ne5 + f4"],
    faqs: [
      { q: "Colle vs London System?", a: "Both system openings; Colle aims for e4 break, London locks the Bf4 in earlier." },
      { q: "Is the Colle good against the King's Indian?", a: "No — Colle works best vs ...d5 setups. Switch to Torre or London vs ...g6." },
    ],
  },
  "torre-attack": {
    id: "torre-attack", slug: "torre-attack", searchVolume: 1300,
    name: "Torre Attack", eco: "A46–D03", category: "queen's pawn", difficulty: "intermediate",
    startingMoves: "1.d4 Nf6 2.Nf3 e6 3.Bg5",
    description: "Solid system with Bg5 pin — easier than Trompowsky, deeper than London.",
    longTitle: "Torre Attack — System Opening with Bg5",
    longDescription: "Torre Attack (1.d4 Nf6 2.Nf3 e6 3.Bg5) — system opening pinning Black's knight from move 3.",
    keyIdeas: ["Pin the f6 knight with Bg5 early", "Aim for c3 + Nbd2 + e4 in the center", "Use h3 + Bh4 to keep the pin alive", "Trade dark-squared bishops on f6 if Black contests"],
    faqs: [
      { q: "Torre vs Trompowsky?", a: "Torre adds Nf3 first; Tromp keeps the f-pawn flexible for f3-e4 advances." },
      { q: "Is the Torre good for tournaments?", a: "Excellent — minimal theory, clear plans, crushing wins vs unprepared opponents." },
    ],
  },
  "kings-indian-attack": {
    id: "kings-indian-attack", slug: "kings-indian-attack", searchVolume: 2400,
    name: "King's Indian Attack", eco: "A07", category: "system", difficulty: "intermediate",
    startingMoves: "1.Nf3 d5 2.g3 Nf6 3.Bg2",
    description: "Reverse King's Indian as White — fianchetto, e4, Re1, h4 attack. Bobby Fischer's favorite.",
    longTitle: "King's Indian Attack — Fischer's Universal Setup",
    longDescription: "King's Indian Attack (1.Nf3 + 2.g3 + 3.Bg2) — universal White setup vs almost any Black formation.",
    keyIdeas: ["Fianchetto + e4 / Re1 / Nbd2 setup", "Aim for h4-h5 kingside attack", "Use universal setup vs French, Sicilian, ...d5", "Convert development advantage into kingside crush"],
    famousGames: ["Fischer vs Myagmarsuren 1967 — Sousse Interzonal", "Fischer vs Ulhmann 1970"],
    faqs: [
      { q: "KIA vs KID?", a: "Same setup, different colors — KIA = playing the King's Indian as White (with extra tempo)." },
      { q: "When to play the KIA?", a: "Vs French, Sicilian, ...d5 — basically any setup where Black doesn't fianchetto first." },
    ],
  },
  "reti-opening": {
    id: "reti-opening", slug: "reti-opening", searchVolume: 4400,
    name: "Réti Opening", eco: "A04–A09", category: "system", difficulty: "intermediate",
    startingMoves: "1.Nf3 d5 2.c4",
    description: "Attack ...d5 from the wing — hypermodern, flexible, transposes everywhere.",
    longTitle: "Réti Opening — Hypermodern 1.Nf3",
    longDescription: "Réti Opening (1.Nf3 d5 2.c4) — hypermodern attack on ...d5 from the wing. Flexible, transpositional.",
    keyIdeas: ["Attack ...d5 from the wing with c4", "Fianchetto on g2 for long-diagonal pressure", "Transpose into Catalan, English, or KID Attack", "Use cxd5 to open the c-file"],
    faqs: [
      { q: "Réti vs English?", a: "Réti starts 1.Nf3; English starts 1.c4. They often transpose into each other." },
      { q: "Is the Réti hard to play?", a: "Flexible but requires deep transpositional knowledge. Reward: opponent rarely knows it." },
    ],
  },
  "larsen-opening": {
    id: "larsen-opening", slug: "larsen-opening", searchVolume: 1300,
    name: "Larsen's Opening", eco: "A01", category: "flank", difficulty: "intermediate",
    startingMoves: "1.b3",
    description: "Fianchetto the queen's bishop on move 1 — Bent Larsen's offbeat universal setup.",
    longTitle: "Larsen's Opening — Nimzo-Larsen Attack",
    longDescription: "Larsen's Opening (1.b3) — Bent Larsen's surprise weapon. Fianchetto the b2-bishop on move 1.",
    keyIdeas: ["Fianchetto the bishop to b2 immediately", "Aim the bishop at the long a1-h8 diagonal", "Combine with Nf3 + e3 universal setup", "Punish slow Black play with c4 + d4"],
    faqs: [
      { q: "Why play 1.b3?", a: "Almost zero theory required from your opponent. Pure middlegame chess from move 1." },
      { q: "Is 1.b3 sound?", a: "Yes — Larsen, Nakamura, and Carlsen have all used it at top level." },
    ],
  },
  "bird-opening": {
    id: "bird-opening", slug: "bird-opening", searchVolume: 1900,
    name: "Bird's Opening", eco: "A02–A03", category: "flank", difficulty: "intermediate",
    startingMoves: "1.f4",
    description: "Reversed Dutch — kingside space and aim every piece at the Black king.",
    longTitle: "Bird's Opening — Reversed Dutch (1.f4)",
    longDescription: "Bird's Opening (1.f4) — reversed Dutch with an extra tempo. Kingside attack from move 1.",
    keyIdeas: ["Stake out kingside with f4 immediately", "Aim for Stonewall structure with c3, d4, e3", "Use From's Gambit (1...e5) defense lines carefully", "Fianchetto the queen's bishop for support"],
    faqs: [
      { q: "Is the Bird's Opening risky?", a: "1.f4 weakens e1-h4 diagonal. From's Gambit (1...e5 2.fxe5 d6) is critical to know." },
      { q: "Bird vs Dutch?", a: "Same setup mirrored — Bird gets one tempo more, which matters." },
    ],
  },
  "italian-giuoco-piano": {
    id: "italian-giuoco-piano", slug: "giuoco-piano", searchVolume: 2900,
    name: "Giuoco Piano", eco: "C53–C54", category: "open game", difficulty: "beginner",
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5",
    description: "Quietly build up with c3 + d3 — the modern Italian's main scoring system.",
    longTitle: "Giuoco Piano — Modern Italian Slow Burn",
    longDescription: "Giuoco Piano (3.Bc4 Bc5) — modern slow Italian with c3 + d3. Carlsen's main 1.e4 weapon recently.",
    keyIdeas: ["Play c3 + d3 for the slow Italian setup", "Develop knights to f3 + d2 (rerouting via Nf1-Ng3)", "Aim for h3 + Re1 + Nbd2-Nf1-Ng3 maneuver", "Convert space advantage into kingside attack"],
    famousGames: ["Carlsen vs Anand 2014 WCC Game 4", "Caruana vs Aronian 2018"],
    faqs: [
      { q: "Giuoco Piano vs Italian Game?", a: "Giuoco Piano = the line 3.Bc4 Bc5. Italian Game refers to the entire 3.Bc4 system." },
      { q: "Why is it 'piano' (slow)?", a: "Because c3 + d3 plays for slow positional pressure rather than tactical fireworks." },
    ],
  },
  "fried-liver-attack": {
    id: "fried-liver-attack", slug: "fried-liver-attack", searchVolume: 18100,
    name: "Fried Liver Attack", eco: "C57", category: "open game", difficulty: "beginner",
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 d5 5.exd5 Nxd5 6.Nxf7",
    description: "Sacrifice the knight on f7 — the most famous beginner trap that every chess player must know.",
    longTitle: "Fried Liver Attack — Famous Knight Sacrifice",
    longDescription: "Fried Liver Attack (1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 d5 5.exd5 Nxd5 6.Nxf7) — the most famous beginner trap.",
    keyIdeas: ["Sacrifice the f7 knight to drag the king out", "Follow with Qf3+ to win back material", "Aim for a king-hunt with Nc3 and d4", "Counter ...Nb4 with c3 + a3 timing"],
    faqs: [
      { q: "How does Black avoid the Fried Liver?", a: "Play 5...Na5! (Polerio Defense) instead of 5...Nxd5 — the engine-approved equalizer." },
      { q: "Is the Fried Liver winning for White?", a: "Only at club level. Engines say it's equal with perfect defense, but it's brutal in practice." },
    ],
  },
  "stafford-gambit": {
    id: "stafford-gambit", slug: "stafford-gambit", searchVolume: 22200,
    name: "Stafford Gambit", eco: "C42", category: "open game", difficulty: "intermediate",
    startingMoves: "1.e4 e5 2.Nf3 Nf6 3.Nxe5 Nc6",
    description: "Eric Rosen's viral YouTube weapon — sacrifice a pawn for explosive piece activity.",
    longTitle: "Stafford Gambit — YouTube Viral Trap",
    longDescription: "Stafford Gambit (1.e4 e5 2.Nf3 Nf6 3.Nxe5 Nc6) — Eric Rosen's viral pawn sacrifice with brutal traps.",
    keyIdeas: ["Sacrifice ...Nc6 for piece activity", "Aim for ...Bc5, ...Qd6, ...Ng4 attacking setup", "Punish d3? with ...Nxe4 tactics", "Watch for the Qh4+ mating attack"],
    faqs: [
      { q: "Is the Stafford Gambit sound?", a: "No — White is winning with accurate play. But club-level traps make it +400 score for Black in practice." },
      { q: "How to refute the Stafford?", a: "4.Nxc6 dxc6 5.d3 + careful development. Avoid the natural-looking traps with h3, Nc3, Be2." },
    ],
  },
  "halloween-gambit": {
    id: "halloween-gambit", slug: "halloween-gambit", searchVolume: 1900,
    name: "Halloween Gambit", eco: "C46", category: "open game", difficulty: "advanced",
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.Nc3 Nf6 4.Nxe5",
    description: "Sacrifice a knight in the opening — wild surprise weapon that scares unprepared opponents.",
    longTitle: "Halloween Gambit — Knight Sac Surprise",
    longDescription: "Halloween Gambit (1.e4 e5 2.Nf3 Nc6 3.Nc3 Nf6 4.Nxe5) — sacrifice a full knight for central pawn storm.",
    keyIdeas: ["Sacrifice the knight on e5 for a pawn duo", "Push e4-e5 to chase the f6 knight", "Aim for Bc4 + d4 + f4 attacking setup", "Use the time advantage for a king-hunt"],
    faqs: [
      { q: "Is the Halloween Gambit sound?", a: "Objectively losing — but extremely tricky over the board. Pure surprise weapon." },
      { q: "How does Black survive?", a: "4...Nxe5 5.d4 Nc6 6.d5 — Black retreats the knight to a calm square and consolidates." },
    ],
  },
  "smith-morra-gambit": {
    id: "smith-morra-gambit", slug: "smith-morra-gambit", searchVolume: 4400,
    name: "Smith-Morra Gambit", eco: "B21", category: "sicilian", difficulty: "intermediate",
    startingMoves: "1.e4 c5 2.d4 cxd4 3.c3",
    description: "Anti-Sicilian gambit — sacrifice a pawn to reach an open Italian-style position vs the Sicilian.",
    longTitle: "Smith-Morra Gambit — Anti-Sicilian Weapon",
    longDescription: "Smith-Morra Gambit (1.e4 c5 2.d4 cxd4 3.c3) — sacrifice a pawn to dodge Sicilian theory entirely.",
    keyIdeas: ["Sacrifice a pawn to get open lines vs the Sicilian", "Develop Nc3, Bc4, and Nf3 with Italian-style pressure", "Aim Bc4 at f7 immediately", "Use the open c-file for Rxc6 sacrifice ideas"],
    faqs: [
      { q: "Is the Smith-Morra refuted?", a: "Black has equalizing lines (3...Nf6 4.e5 Nd5 or 3...d3) but the practical scoring is brutal." },
      { q: "Why play the Smith-Morra?", a: "Skip 100+ pages of Sicilian theory and play active piece chess from move 3." },
    ],
  },
  "danish-gambit": {
    id: "danish-gambit", slug: "danish-gambit", searchVolume: 2900,
    name: "Danish Gambit", eco: "C21", category: "open game", difficulty: "intermediate",
    startingMoves: "1.e4 e5 2.d4 exd4 3.c3",
    description: "Sacrifice 1-2 pawns for open lines and bishops aiming at the Black king. Romantic-era classic.",
    longTitle: "Danish Gambit — Romantic Pawn Sacrifice",
    longDescription: "Danish Gambit (1.e4 e5 2.d4 exd4 3.c3) — sacrifice up to 2 pawns for monstrous bishop pressure.",
    keyIdeas: ["Sacrifice the c-pawn (and sometimes b-pawn) for development", "Aim Bc4 + Bb2 at the Black king on the long diagonals", "Use open lines for direct attacks", "Convert positional pressure into mate"],
    faqs: [
      { q: "Is the Danish Gambit sound?", a: "Black equalizes with 5...d5 (Schlechter Defense). But practical chaos favors the gambiteer." },
      { q: "Danish vs Smith-Morra?", a: "Danish is vs 1...e5; Smith-Morra is vs 1...c5. Same idea — open lines for active piece play." },
    ],
  },
  "english-opening-symmetrical": {
    id: "english-opening-symmetrical", slug: "english-symmetrical", searchVolume: 880,
    name: "English Symmetrical Variation", eco: "A30–A39", category: "english", difficulty: "intermediate",
    startingMoves: "1.c4 c5",
    description: "Mirror White's setup with the Symmetrical English — battle for the d5 square.",
    longTitle: "English Symmetrical — Mirror Strategy",
    longDescription: "English Symmetrical (1.c4 c5) — Black mirrors White and battles for d5. Hedgehog setups common.",
    keyIdeas: ["Mirror White's setup symmetrically", "Battle for the d5 square with knights on c3/c6", "Use Hedgehog formation (...a6, ...e6, ...d6)", "Break symmetry only when concrete benefit appears"],
    faqs: [
      { q: "Is the Symmetrical English drawish?", a: "Surface-level yes, but Hedgehog and ...e5 breaks create deep imbalances." },
      { q: "Best Hedgehog setup?", a: "...e6, ...d6, ...a6, ...b6, ...Bb7 — flexible coiled-spring waiting for White to overextend." },
    ],
  },
};
