// SEO long-tail content articles. Slugs target high-volume Google chess queries
// surfaced via Semrush keyword research (e.g. "how to play chess" = 40,500/mo).

export interface ArticleSection {
  heading: string;
  body: string; // plain text paragraphs separated by "\n\n"
}

export interface ArticleStep {
  name: string;
  text: string;
}

export interface LearnArticle {
  slug: string;
  title: string;          // <60 chars, contains primary keyword
  metaDescription: string; // <160 chars
  h1: string;
  keyword: string;        // primary target keyword
  intro: string;
  steps?: ArticleStep[];   // for HowTo schema
  sections: ArticleSection[];
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
  updated: string;        // ISO date
}

export const LEARN_ARTICLES: LearnArticle[] = [
  {
    slug: "how-to-play-chess",
    title: "How to Play Chess — Rules for Beginners (2026 Guide)",
    metaDescription: "Learn how to play chess from scratch: piece moves, special rules, check, checkmate and how to win. Beginner-friendly guide with a free online board.",
    h1: "How to Play Chess — A Complete Beginner's Guide",
    keyword: "how to play chess",
    intro: "Chess is a two-player strategy game played on an 8×8 board with 16 pieces per side. The goal is to checkmate the opponent's king — to put it under attack with no legal escape. This guide walks you through the entire ruleset in about ten minutes, then lets you jump straight into a free online game against a bot.",
    steps: [
      { name: "Set up the board", text: "Place the board so each player has a light square on the bottom-right corner. Pawns go on the second rank. Rooks in the corners, knights next to them, bishops, then queen on her color (white queen on a light square, black queen on a dark square), and king on the remaining square." },
      { name: "Learn how each piece moves", text: "Pawns move forward one square (two on the first move) and capture diagonally. Rooks move in straight lines. Bishops move diagonally. The queen combines rook and bishop. Knights jump in an L-shape. The king moves one square in any direction." },
      { name: "Understand special moves", text: "Castling (king and rook swap to safety), en passant (a pawn capture immediately after an opposing pawn's two-square advance), and promotion (a pawn that reaches the last rank becomes any piece, usually a queen)." },
      { name: "Recognize check and checkmate", text: "When the king is attacked, that's check — you must respond. If there's no legal way to stop the attack, that's checkmate and the game ends." },
      { name: "Play your first game", text: "Open the free MasterChess board, choose a beginner bot, and play. Use the analysis afterwards to see your blunders and best moves." },
    ],
    sections: [
      {
        heading: "Why chess is worth learning in 2026",
        body: "Chess sharpens pattern recognition, calculation and emotional control. It's the only mainstream game where a child can beat a world champion if they outplay them — pure skill, no luck. Online chess has exploded since 2020 thanks to streamers and Netflix, and the ecosystem is bigger than ever. Best part: it's free to play forever, and you only need a browser.",
      },
      {
        heading: "The objective: checkmate",
        body: "You don't have to capture the king — you only have to make sure it can never escape an attack. Stalemate (no legal moves but not in check) is a draw, so a beginner trick is to keep an escape square for the losing side. Mating patterns like the back-rank mate, the smothered mate, and the two-rook ladder are the first ones to memorize.",
      },
      {
        heading: "First-move principles",
        body: "Control the center with a pawn (e4 or d4), develop knights before bishops, castle within the first ten moves to protect your king, and connect your rooks. Don't move the same piece twice in the opening unless you have to. These four rules alone beat 95% of casual opponents.",
      },
      {
        heading: "Practice plan for your first 30 days",
        body: "Play 3 games per day against a 600-rated bot, then review each game with the engine. After a week, increase to 800. By day 30 you should comfortably handle a 1000 bot and recognize a back-rank mate from across the room.",
      },
    ],
    faqs: [
      { q: "Is chess hard to learn?", a: "The rules take 10 minutes. Becoming good takes years, but you'll enjoy your first wins on day one." },
      { q: "Can I play chess online for free?", a: "Yes. MasterChess and similar platforms offer unlimited free games against people or bots, no signup required to try." },
      { q: "What's the best age to start chess?", a: "Kids can grasp the rules around age 4–5. Adults can start at any age — many strong amateurs began after 30." },
      { q: "How long is a chess game?", a: "Anywhere from 1 minute (bullet) to over 6 hours (classical). Most online games last 10–15 minutes." },
    ],
    relatedSlugs: ["how-to-set-up-chess-board", "how-to-castle-in-chess", "play-chess-online-with-friends"],
    updated: "2026-05-14",
  },
  {
    slug: "how-to-set-up-chess-board",
    title: "How to Set Up a Chess Board (Correct Way + Diagram)",
    metaDescription: "Set up a chess board the correct way: light square on the right, queen on her color, pawns on the second rank. Quick visual guide with a free online board.",
    h1: "How to Set Up a Chess Board Correctly",
    keyword: "how to set up a chess board",
    intro: "Almost every beginner sets the chess board up wrong at least once — usually by flipping the king and queen, or by orienting the board with a dark square on the right. This 60-second guide fixes that for life, then drops you into a free online setup to practice.",
    steps: [
      { name: "Light square on the right", text: "Rotate the board so each player has a light (white) square on their bottom-right corner. Remember the rhyme: 'light on right'." },
      { name: "Pawns on the second rank", text: "Place all 8 pawns of each color on the second row from that player. They form the front wall." },
      { name: "Rooks in the corners", text: "Both rooks (the castle-shaped pieces) go on the corners of the back rank." },
      { name: "Knights next to the rooks", text: "Place the knights (horse-shaped pieces) just inside the rooks." },
      { name: "Bishops next to the knights", text: "Place the bishops just inside the knights, flanking the central two squares." },
      { name: "Queen on her color", text: "White queen on the light central square, black queen on the dark central square. Mnemonic: 'queen on color'." },
      { name: "King on the last square", text: "The king takes the remaining central square. Kings face each other across the board." },
    ],
    sections: [
      {
        heading: "Why orientation matters",
        body: "If the board is rotated 90°, every move you learn from a book or video will be mirrored. Squares like e4 won't exist where they should. Tournament organizers will also stop the clock and reset the board, which is embarrassing on round one.",
      },
      {
        heading: "Common setup mistakes",
        body: "1) Swapping king and queen — fix with the 'queen on color' rule. 2) Board flipped to dark-on-right — fix with 'light on right'. 3) Bishops on the wrong central diagonal because the king and queen are swapped — both errors at once. Check your setup against any starting position on MasterChess before move one.",
      },
      {
        heading: "Setting up an analog vs. an online board",
        body: "Online, the board orients itself — you only worry about which color you're playing. Offline, run through this checklist every time, especially under tournament pressure where small mistakes cost games.",
      },
    ],
    faqs: [
      { q: "Does white always go first in chess?", a: "Yes, white moves first. This gives a small but measurable advantage at every level." },
      { q: "Which square does the queen go on?", a: "The queen always starts on her own color: white queen on a light square, black queen on a dark square." },
      { q: "Is there a light square in the bottom-right corner?", a: "Yes — that's how you know the board is oriented correctly. If you see a dark square there, rotate the board 90°." },
    ],
    relatedSlugs: ["how-to-play-chess", "how-to-castle-in-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "how-to-castle-in-chess",
    title: "How to Castle in Chess — Rules, Kingside &amp; Queenside",
    metaDescription: "Learn how to castle in chess: kingside vs queenside, the four conditions, and when to castle early or delay. Free interactive board to practice.",
    h1: "How to Castle in Chess (Without Breaking the Rules)",
    keyword: "how to castle in chess",
    intro: "Castling is the only move in chess that lets you move two pieces at once. It's also the single most useful tool for keeping your king safe — and the move beginners most often skip or mis-execute. Here's everything you need to know in under five minutes.",
    steps: [
      { name: "Confirm neither the king nor the chosen rook has moved", text: "Castling is forbidden once the king has moved, or once the involved rook has moved. The other rook can still castle." },
      { name: "Clear all squares between the king and rook", text: "There must be no pieces between them. For kingside that's two squares (f1, g1); for queenside that's three (b1, c1, d1)." },
      { name: "Make sure you are not in check", text: "You cannot castle out of check. Resolve the check first, then castle later." },
      { name: "Check the squares the king crosses are not attacked", text: "The king cannot pass through or land on a square attacked by an enemy piece. The rook is allowed to cross attacked squares." },
      { name: "Move the king two squares toward the rook, then jump the rook to the king's other side", text: "On a digital board, drag the king two squares — the rook moves automatically." },
    ],
    sections: [
      {
        heading: "Kingside vs queenside castling",
        body: "Kingside (short) castling lands the king on g1/g8 and is faster and safer because only two squares clear. Queenside (long) castling lands the king on c1/c8 and the rook on d1/d8 — slower, but the rook lands in the center, which is an advantage in open positions.",
      },
      {
        heading: "When to castle early",
        body: "Castle within the first 10 moves in almost every opening except very specific theoretical lines. A king stranded in the center invites tactical disasters: pinned bishops, exposed queens, and tactics that swing games in three moves.",
      },
      {
        heading: "When to delay castling",
        body: "If your opponent has castled into a weak king position, sometimes it pays to keep your king flexible and attack first. This is advanced territory — under 1500 ELO, just castle early.",
      },
    ],
    faqs: [
      { q: "Can you castle through check?", a: "No. The king cannot pass through or land on a square attacked by an enemy piece." },
      { q: "Can you castle if your rook is attacked?", a: "Yes. Only the king's path matters, not the rook's." },
      { q: "Can you castle out of check?", a: "No. You must resolve the check first." },
      { q: "Is castling kingside or queenside better?", a: "Kingside is generally safer; queenside puts the rook in the center but exposes the king more. Choose based on the pawn structure." },
    ],
    relatedSlugs: ["how-to-play-chess", "how-to-set-up-chess-board"],
    updated: "2026-05-14",
  },
  {
    slug: "play-chess-online-with-friends",
    title: "Play Chess Online With Friends — Free, No Signup",
    metaDescription: "Play chess online with friends free in your browser. Share a link, choose a time control, and start playing. No download, no signup required.",
    h1: "Play Chess Online With Friends — Free in Your Browser",
    keyword: "play chess online with friends",
    intro: "You don't need an app or an account to play chess online with a friend. MasterChess lets you create a private game, copy the invite link, and start playing in under 30 seconds. Pick a time control, share the URL, and it's on.",
    steps: [
      { name: "Open the Play page", text: "Go to /play on MasterChess." },
      { name: "Choose 'Play a friend'", text: "Pick a time control (Bullet 1+0, Blitz 5+0, Rapid 10+0, or custom)." },
      { name: "Copy the invite link", text: "MasterChess generates a unique private link for the match." },
      { name: "Send it to your friend", text: "Drop the link in WhatsApp, Discord, Telegram, iMessage — whatever you use." },
      { name: "Play when they join", text: "The game starts as soon as your friend opens the link. Voice or video chat alongside if you want." },
    ],
    sections: [
      {
        heading: "Why play online instead of in person",
        body: "Online chess automatically enforces all the rules (no illegal moves), keeps your time, records every move for analysis, and works across time zones. Your phone or laptop is enough — no board to pack.",
      },
      {
        heading: "Best time controls for friend games",
        body: "Blitz 5+0 is the sweet spot — fast enough to keep things lively, slow enough to think. For absolute beginners, try Rapid 10+0 so neither of you flags. For seasoned blitz players, try Bullet 1+0 for chaos.",
      },
      {
        heading: "How to play chess with friends on a phone",
        body: "MasterChess is fully responsive — the same link works on iPhone, Android, and desktop. Drag the pieces with your finger, tap to move, or use long-press for a precise drag.",
      },
    ],
    faqs: [
      { q: "Do I need an account to play with a friend?", a: "No. The link works for guests. Sign up only if you want your rating and history saved." },
      { q: "Is it free to play chess online with friends?", a: "Yes, fully free, unlimited games, no ads on the board." },
      { q: "Can I play with my friend on a different device?", a: "Yes — desktop, iPhone, Android, tablet all work through the same shared link." },
      { q: "Can we voice chat during the game?", a: "MasterChess supports text chat. For voice, use Discord, WhatsApp, or FaceTime alongside." },
    ],
    relatedSlugs: ["how-to-play-chess", "how-to-castle-in-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "best-chess-openings-for-beginners",
    title: "Best Chess Openings for Beginners (Top 5, Easy to Learn)",
    metaDescription: "The 5 best chess openings for beginners — Italian Game, London System, Caro-Kann, Scandinavian, and King's Indian. With move-by-move plans and a free trainer.",
    h1: "Best Chess Openings for Beginners",
    keyword: "best chess openings for beginners",
    intro: "You don't need to memorize 30 moves of theory to play good chess as a beginner. You need a small repertoire of solid, principled openings you actually understand. These five openings cover white and black, give you healthy positions almost every game, and grow with you up to club level.",
    sections: [
      { heading: "1. The Italian Game (for White)", body: "1.e4 e5 2.Nf3 Nc6 3.Bc4. Develop pieces fast, target the f7 weakness, castle short, and play in the center. The Italian teaches every classical principle without weird traps to memorize." },
      { heading: "2. The London System (for White)", body: "1.d4, 2.Nf3, 3.Bf4, 4.e3, 5.Bd3, 6.c3, 7.Nbd2, 0-0. Same setup almost every game. Hard to lose in the opening, easy to learn, used by world champions like Magnus Carlsen." },
      { heading: "3. The Caro-Kann (for Black vs 1.e4)", body: "1.e4 c6. You support …d5 with a pawn instead of a knight, you avoid the sharpest Sicilian theory, and you get a rock-solid pawn structure. Anand and Karpov made careers with it." },
      { heading: "4. The Scandinavian (for Black vs 1.e4)", body: "1.e4 d5. Immediately challenges the center. After 2.exd5 Qxd5 3.Nc3 Qa5, black has a clear plan: develop, castle, push …e5 or …c5. Almost zero theory, big upside." },
      { heading: "5. The King's Indian Defense (for Black vs 1.d4)", body: "1.d4 Nf6 2.c4 g6 3.Nc3 Bg7 4.e4 d6 5.Nf3 0-0. A fierce counter-attacking system used by Kasparov and Fischer. Black accepts a space disadvantage in exchange for a kingside pawn storm later." },
      { heading: "How to learn an opening properly", body: "Don't memorize variations — understand the ideas. For every opening, learn: 1) the first 5-7 moves, 2) the typical pawn structure, 3) where your pieces want to go, 4) the main plan in the middlegame. The MasterChess Opening Trainer drills all of this with Stockfish-verified lines." },
    ],
    faqs: [
      { q: "What is the easiest chess opening to learn?", a: "The London System. The same setup works against almost any black response, so you skip 90% of memorization." },
      { q: "Should beginners memorize openings?", a: "No. Memorize the first 4–5 moves and learn the ideas. Tactics and endgames matter far more under 1500 ELO." },
      { q: "What opening does Magnus Carlsen play?", a: "Magnus plays almost everything, but he's known for popularizing the London System and the Italian Game at the top level." },
    ],
    relatedSlugs: ["queens-gambit-opening", "sicilian-defense-explained", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "queens-gambit-opening",
    title: "Queen's Gambit Opening — Lines, Ideas, and How to Play It",
    metaDescription: "The Queen's Gambit explained: Accepted, Declined, Slav. Main lines, ideas, traps, and a free Stockfish-verified trainer to practice it move by move.",
    h1: "The Queen's Gambit Opening — Full Guide",
    keyword: "queen's gambit opening",
    intro: "The Queen's Gambit (1.d4 d5 2.c4) is one of the oldest and most respected openings in chess. It's not really a 'gambit' — white almost always recovers the pawn — but the name stuck. After the Netflix series, it became a cultural icon. Here's how to actually play it.",
    sections: [
      { heading: "Queen's Gambit Accepted (QGA)", body: "1.d4 d5 2.c4 dxc4. Black grabs the pawn but can't hold it. White plays 3.e4 or 3.Nf3 and dominates the center, then recovers c4 at leisure. Practical and sharp." },
      { heading: "Queen's Gambit Declined (QGD)", body: "1.d4 d5 2.c4 e6. The mainline. Black builds a solid pawn chain (d5/e6/c6) and slowly equalizes. Used by every world champion at some point — extremely sound." },
      { heading: "Slav Defense", body: "1.d4 d5 2.c4 c6. Like the QGD but the light-squared bishop is freed before being locked in. The Slav is the choice of modern elite players." },
      { heading: "White's typical plan", body: "Develop knights (Nc3, Nf3), bishop to g5 or f4, castle short, and push for e4 in the middlegame. The pressure on d5 is permanent — black has to deal with it for 20 moves." },
      { heading: "Common traps to know", body: "The Elephant Trap in QGD, the Marshall Trap in the Slav, and the 'Cambridge Springs' counterattack. Every Queen's Gambit player should see these once so they don't fall into them." },
    ],
    faqs: [
      { q: "Is the Queen's Gambit good for beginners?", a: "Yes — it teaches central control and piece coordination better than any other 1.d4 opening." },
      { q: "Should you accept the Queen's Gambit?", a: "It's playable but theoretically slightly worse for black. Most strong players decline with 2…e6 or play the Slav." },
      { q: "Is the Queen's Gambit a real gambit?", a: "Technically yes, but white almost always recovers the pawn within a few moves. It's a 'temporary' gambit." },
    ],
    relatedSlugs: ["best-chess-openings-for-beginners", "sicilian-defense-explained", "italian-game-opening"],
    updated: "2026-05-14",
  },
  {
    slug: "sicilian-defense-explained",
    title: "Sicilian Defense Explained — Variations, Plans, Theory",
    metaDescription: "The Sicilian Defense (1.e4 c5) explained: Najdorf, Dragon, Sveshnikov, Taimanov. Plans, key ideas, and a free Stockfish trainer to drill the main lines.",
    h1: "The Sicilian Defense — Black's Sharpest Weapon",
    keyword: "sicilian defense",
    intro: "The Sicilian (1.e4 c5) is the most popular response to 1.e4 at every level above 1500. Black immediately fights for the center on an asymmetric pawn structure, leading to unbalanced, fighting games. It's the favorite opening of Kasparov, Fischer, and Carlsen.",
    sections: [
      { heading: "Why the Sicilian wins games", body: "1.e4 c5 gives black a half-open c-file, a queenside pawn majority, and central control without copying white. The cost: it's the most theory-heavy opening in chess." },
      { heading: "Najdorf Variation", body: "1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6. The crown jewel — Fischer's lifelong weapon. Black plays …a6 to prepare …e5 and …b5 with massive flexibility. Theory goes 20+ moves deep." },
      { heading: "Dragon Variation", body: "1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 g6. The fianchettoed bishop on g7 stares down white's king. Yugoslav Attack vs Dragon is one of the sharpest battles in chess." },
      { heading: "Sveshnikov Variation", body: "1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 e5. Modern, dynamic, and Magnus Carlsen's choice in his title match vs Caruana." },
      { heading: "Closed and Anti-Sicilians", body: "If you don't want to play the Open Sicilian, study the Alapin (2.c3), Smith-Morra Gambit (2.d4), or Closed Sicilian (2.Nc3). These bypass the main theory and create your own game." },
    ],
    faqs: [
      { q: "Is the Sicilian Defense good for beginners?", a: "Below 1400 ELO, the Sicilian's theory burden is more punishment than reward. Try the Caro-Kann or Scandinavian first." },
      { q: "What's the best Sicilian variation?", a: "The Najdorf is statistically the most successful at all levels, but the Sveshnikov is the modern elite favorite." },
      { q: "Is the Sicilian Defense risky?", a: "It's sharper than other defenses but objectively sound — black has been winning with it for 70 years." },
    ],
    relatedSlugs: ["best-chess-openings-for-beginners", "queens-gambit-opening", "italian-game-opening"],
    updated: "2026-05-14",
  },
  {
    slug: "italian-game-opening",
    title: "Italian Game Opening — Lines, Ideas, and Best Plans",
    metaDescription: "The Italian Game (1.e4 e5 2.Nf3 Nc6 3.Bc4) explained: Giuoco Piano, Evans Gambit, Two Knights. Plans, traps, and a free Stockfish-verified trainer.",
    h1: "The Italian Game — Classical Chess at Its Best",
    keyword: "italian game chess",
    intro: "The Italian Game (1.e4 e5 2.Nf3 Nc6 3.Bc4) is the oldest documented chess opening — written down in 1497. It's also one of the best beginner openings, teaching every classical principle: fast development, central control, kingside attack, and safe castling.",
    sections: [
      { heading: "Giuoco Piano (the 'Quiet Game')", body: "3…Bc5 4.c3 Nf6 5.d3. Slow buildup, both kings castle, then white plays h3, Re1, Nbd2, Nf1, Ng3, pointing the army at the black king. Modern, positional, very playable." },
      { heading: "Two Knights Defense", body: "3…Nf6. Sharper. White can play 4.Ng5 attacking f7, leading to wild tactical games. Black has to know the theory or lose quickly." },
      { heading: "Evans Gambit", body: "4.b4 — Garry Kasparov's surprise weapon. White sacrifices a pawn for huge development and an attack on f7. One of the most beautiful openings in chess." },
      { heading: "Typical Italian Game plans", body: "For white: castle short, play h3 to prevent …Bg4 pins, then maneuver the knight to g3 and launch a kingside attack. For black: counterattack on the queenside or trade pieces and play for equality." },
    ],
    faqs: [
      { q: "Is the Italian Game still good in 2026?", a: "Yes — it's been a top-level opening for 500 years and Magnus Carlsen plays it regularly." },
      { q: "Italian Game vs Ruy Lopez — which is better?", a: "Both are theoretically excellent. The Italian is friendlier for beginners; the Ruy Lopez is sharper and more theoretical." },
      { q: "What's the Fried Liver Attack?", a: "A famous Two Knights line: 4.Ng5 d5 5.exd5 Nxd5 6.Nxf7. White sacrifices a knight for a king-hunt — devastating against unprepared black players." },
    ],
    relatedSlugs: ["best-chess-openings-for-beginners", "queens-gambit-opening", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-piece-names-and-moves",
    title: "Chess Piece Names and Moves — Complete Visual Guide",
    metaDescription: "Every chess piece explained: king, queen, rook, bishop, knight, pawn. How they move, capture, and combine. Free interactive board to practice each piece.",
    h1: "Chess Pieces — Names, Moves, and Values",
    keyword: "chess piece names",
    intro: "Chess has 6 piece types, each with a unique movement pattern. Memorizing them takes 10 minutes; mastering how they work together takes a lifetime. Here's the complete guide, with piece values, special rules, and an interactive board.",
    sections: [
      { heading: "King (♔ / ♚) — value: infinite", body: "Moves one square in any direction. Cannot move into check. The whole game revolves around protecting it. Castling is the only time it moves two squares." },
      { heading: "Queen (♕ / ♛) — value: 9 points", body: "Moves any number of squares in any direction: horizontally, vertically, or diagonally. Combines rook + bishop. By far the strongest piece — losing your queen usually means losing the game." },
      { heading: "Rook (♖ / ♜) — value: 5 points", body: "Moves any number of squares horizontally or vertically. Each player starts with two. Rooks are devastating on open files and the 7th rank." },
      { heading: "Bishop (♗ / ♝) — value: 3 points", body: "Moves any number of squares diagonally. Each player has a light-square and a dark-square bishop. The bishop pair (both bishops alive) is worth roughly half a pawn extra." },
      { heading: "Knight (♘ / ♞) — value: 3 points", body: "Moves in an L-shape: 2 squares in one direction, then 1 square perpendicular. The only piece that jumps over others. Best on outposts in the center." },
      { heading: "Pawn (♙ / ♟) — value: 1 point", body: "Moves forward 1 square (or 2 from the starting rank), captures diagonally. Cannot move backward. Promotes to any piece (usually a queen) on reaching the last rank. En passant is a special pawn-only capture." },
    ],
    faqs: [
      { q: "Which chess piece is the most powerful?", a: "The queen — worth 9 points and able to control 27 squares in the center of an empty board." },
      { q: "Can a pawn become any piece?", a: "Yes — when a pawn reaches the 8th rank it promotes to a queen, rook, bishop, or knight. Choosing a knight is rare but sometimes wins immediately ('underpromotion')." },
      { q: "How many chess pieces are there per side?", a: "16: 8 pawns, 2 rooks, 2 knights, 2 bishops, 1 queen, 1 king." },
    ],
    relatedSlugs: ["how-to-play-chess", "how-to-set-up-chess-board", "chess-piece-values"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-piece-values",
    title: "Chess Piece Values — How Much Is Each Piece Worth?",
    metaDescription: "Pawn 1, knight 3, bishop 3, rook 5, queen 9 — and the exceptions every player should know. Plus how piece values change in the endgame.",
    h1: "Chess Piece Values (and When They Change)",
    keyword: "chess piece values",
    intro: "Every chess piece has a relative value that helps you decide whether a trade is good. The classical numbers — pawn 1, knight 3, bishop 3, rook 5, queen 9 — are a great starting point, but reality is more nuanced. Here's the full picture.",
    sections: [
      { heading: "The standard values", body: "Pawn = 1, Knight = 3, Bishop = 3, Rook = 5, Queen = 9, King = infinite (cannot be captured). Memorize these; they decide 80% of trades." },
      { heading: "When values change", body: "Bishop pair = +0.5 bonus. Knight outposts deep in enemy territory = closer to 4. Rook on the 7th rank = closer to 6. Passed pawns near promotion = up to 5 or more. A queen down a 'bad bishop' may be only 8." },
      { heading: "Practical trade rule", body: "Trade when you're ahead in material to simplify into a winning endgame. Avoid trades when you're behind — keep complications on the board." },
    ],
    faqs: [
      { q: "Is a bishop better than a knight?", a: "Slightly — but it depends on the position. Bishops thrive in open positions; knights thrive in closed ones." },
      { q: "How much is a queen worth?", a: "9 points, equivalent to 3 minor pieces or a rook plus two pawns." },
      { q: "Is a rook worth a knight and a bishop?", a: "Roughly equal (5 vs 6) but two minor pieces usually outperform a rook in the middlegame." },
    ],
    relatedSlugs: ["chess-piece-names-and-moves", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-notation-explained",
    title: "Chess Notation Explained — Read & Write Algebraic Moves",
    metaDescription: "Learn chess notation in 5 minutes: algebraic notation, piece symbols, captures, check, castling, and PGN. Read any chess book or game on the planet.",
    h1: "Chess Notation Explained — A 5-Minute Guide",
    keyword: "chess notation",
    intro: "Chess notation is how every game on the planet is recorded. Once you read it, every chess book, video, and online database opens up. The modern standard is 'algebraic notation', and it takes about 5 minutes to learn.",
    sections: [
      { heading: "Files and ranks", body: "Files (columns) are labeled a–h from white's left to right. Ranks (rows) are 1–8 from white's side. Every square has a unique name like e4, h7, a1." },
      { heading: "Piece symbols", body: "K = King, Q = Queen, R = Rook, B = Bishop, N = Knight. Pawns get no letter. So Nf3 means 'knight to f3', e4 means 'pawn to e4'." },
      { heading: "Captures, check, and special moves", body: "x = capture (Nxe5 = knight takes e5), + = check, # = checkmate, 0-0 = kingside castle, 0-0-0 = queenside castle, = denotes promotion (e8=Q)." },
      { heading: "PGN — the file format for full games", body: "PGN ('Portable Game Notation') stores moves, players, result, and metadata. It's plaintext, opens in any analysis tool, and is the universal language of chess databases." },
    ],
    faqs: [
      { q: "What's the difference between algebraic and descriptive notation?", a: "Algebraic is modern (e4, Nf3). Descriptive (P-K4, N-KB3) is archaic and only appears in pre-1980 books." },
      { q: "How do I record an en passant capture?", a: "Like a normal pawn capture. exd6 (e.p.) is sometimes written for clarity." },
      { q: "What does '!' or '?' mean after a move?", a: "! = good move, !! = brilliant, ? = mistake, ?? = blunder, !? = interesting, ?! = dubious." },
    ],
    relatedSlugs: ["how-to-play-chess", "chess-piece-names-and-moves"],
    updated: "2026-05-14",
  },
  {
    slug: "stalemate-vs-checkmate",
    title: "Stalemate vs Checkmate — What's the Difference?",
    metaDescription: "Stalemate is a draw, checkmate is a win — and confusing them costs beginners points every week. The definitive 3-minute explanation, with examples.",
    h1: "Stalemate vs Checkmate (And Why It Matters)",
    keyword: "stalemate vs checkmate",
    intro: "These two positions look almost identical, but one wins the game and the other ends it in a draw. Mixing them up has cost grandmasters tournaments. Here's the difference, with diagrams you can recreate on a free board.",
    sections: [
      { heading: "Checkmate — game over, attacker wins", body: "The king is in check AND has no legal move that escapes the check. The attacking side wins. The game ends immediately." },
      { heading: "Stalemate — game over, draw", body: "The king is NOT in check, but the side to move has no legal move with any piece. The game is drawn. Common when one side is way ahead in material and gets careless." },
      { heading: "How to avoid stalemating your opponent", body: "When you're ahead in the endgame, always give your opponent a legal move. Don't trap their king with no escape unless it's also check. Use your rook or queen to box them in gradually, not all at once." },
      { heading: "How to seek stalemate when losing", body: "If you're down to a king and one piece, look for stalemate tricks. Sacrifice your last piece so the opponent has nothing left to attack with, then maneuver your king into a corner with no legal moves." },
    ],
    faqs: [
      { q: "Is stalemate a win or a draw?", a: "A draw. Neither side gets a point in tournament play (each gets ½)." },
      { q: "Can the king alone cause stalemate?", a: "Yes — a king with no other pieces, surrounded so it has no legal move and isn't in check, is stalemated." },
      { q: "Why is stalemate a draw, not a loss?", a: "Tradition. In some historical variants it was a loss; modern rules (since the 19th century) call it a draw." },
    ],
    relatedSlugs: ["how-to-play-chess", "how-to-castle-in-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "en-passant-rule",
    title: "En Passant Rule — The Weirdest Move in Chess (Explained)",
    metaDescription: "The en passant rule explained simply: when it applies, how to do it, and why it exists. Every beginner gets confused once — here's the fix.",
    h1: "En Passant — Chess's Most Misunderstood Rule",
    keyword: "en passant rule",
    intro: "Every chess player has watched an opponent play en passant and yelled 'that's not a real move!' It is. It's been in the rulebook since 1561. Here's exactly when and how it works.",
    steps: [
      { name: "Your pawn must be on the 5th rank", text: "(4th rank for black). En passant is only possible from this specific row." },
      { name: "Opponent moves a pawn 2 squares forward", text: "It must land DIRECTLY beside your pawn. If it advances only 1 square, en passant is not available." },
      { name: "You capture it as if it had moved 1 square", text: "Your pawn moves diagonally to the square the opponent's pawn passed over. The opponent's pawn is removed." },
      { name: "Use it immediately or lose the right", text: "En passant must be played on the very next move. If you make a different move, you can't go back and do it later." },
    ],
    sections: [
      { heading: "Why does en passant exist?", body: "Before 1561, pawns moved only 1 square at a time. When the 2-square rule was added, players abused it to slip pawns past opposing pawns. En passant was added to keep the original capture logic working." },
      { heading: "Common mistakes", body: "1) Trying to play it 2 moves later — too late. 2) Trying it from the 4th rank as white — wrong rank. 3) Capturing en passant in your head but forgetting to remove the opponent's pawn on the board — only happens IRL." },
    ],
    faqs: [
      { q: "Can you en passant a knight?", a: "No. En passant only captures pawns, only on the move immediately following a 2-square pawn advance." },
      { q: "Is en passant mandatory?", a: "No — you can choose to play it or not. But you must decide on your very next move." },
      { q: "Can black en passant on move 1?", a: "Yes, after 1.e4 d5 2.e5, white's pawn is on the 5th rank. If black later plays …f5, white can capture exf6 en passant." },
    ],
    relatedSlugs: ["how-to-play-chess", "chess-piece-names-and-moves"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-rating-elo-explained",
    title: "Chess Rating Explained — ELO, FIDE, and Online Ratings",
    metaDescription: "Chess ratings explained: ELO formula, FIDE vs USCF vs online ratings, beginner-to-grandmaster levels, and how to climb. Includes a free rating calculator.",
    h1: "Chess Rating Explained (ELO, FIDE & Online)",
    keyword: "chess rating elo",
    intro: "A chess rating is a number that estimates how strong you are. Beat someone stronger, your rating goes up. Lose to someone weaker, it goes down. The math is called the ELO system, and it's been used worldwide since 1960.",
    sections: [
      { heading: "The ELO levels", body: "<800 = beginner, 800–1200 = casual, 1200–1600 = club player, 1600–2000 = strong club, 2000–2200 = expert, 2200–2400 = candidate master, 2400+ = master, 2500+ = grandmaster (with norms), 2800+ = world-class elite." },
      { heading: "FIDE vs online ratings", body: "FIDE is the international over-the-board rating. Online ratings (chess.com, Lichess, MasterChess) are typically 100–300 points higher than FIDE because pools differ. Lichess tends to read higher than chess.com." },
      { heading: "How ratings change after a game", body: "Expected score is calculated from the rating difference. Each player gains or loses K × (actual − expected), where K is typically 20–40 for amateurs and 10 for masters. The bigger the upset, the bigger the swing." },
      { heading: "How to improve your rating fastest", body: "1) Stop blundering pieces — every move, ask 'is this safe?'. 2) Learn 5 endgame patterns (KR vs K, opposition, Lucena, Philidor, Lucena rook endings). 3) Play longer games and review every loss with Stockfish." },
    ],
    faqs: [
      { q: "What is a good chess rating?", a: "1200 is above average. 1600 is a strong club player. 2000 puts you in the top few percent of all players worldwide." },
      { q: "How do you become a grandmaster?", a: "Reach FIDE 2500 and earn three 'GM norms' in international tournaments against other titled players." },
      { q: "Is online rating real?", a: "Yes — within its own pool. A 1500 on chess.com isn't the same as a 1500 FIDE, but it's a real measure of strength within that site." },
    ],
    relatedSlugs: ["how-to-play-chess", "best-chess-openings-for-beginners"],
    updated: "2026-05-14",
  },
  {
    slug: "how-to-improve-at-chess",
    title: "How to Improve at Chess — Proven 30-Day Plan",
    metaDescription: "A proven 30-day plan to improve at chess: blunder-checking, endgames, openings, analysis. Used by club players to jump 200 rating points. Free trainer included.",
    h1: "How to Improve at Chess (30-Day Plan That Works)",
    keyword: "how to improve at chess",
    intro: "Most players spend years on chess and don't improve. A few jump 200 rating points in a month. The difference isn't talent — it's the practice plan. Here's the exact 30-day routine that produces real gains under 1800 ELO.",
    sections: [
      { heading: "Week 1 — Stop blundering", body: "Before every move, ask three questions: 'Is my piece attacked? Can I be checked? Is anything hanging?' This single habit jumps most under-1400 players 100 rating points." },
      { heading: "Week 2 — Learn 5 endgames", body: "King + rook vs king. King + queen vs king. King + pawn vs king (opposition). The Lucena position. The Philidor position. Drill each one until you can mate from any starting square." },
      { heading: "Week 3 — Pick one opening per color", body: "White: the London System. Black vs e4: the Caro-Kann. Black vs d4: the Slav. Play only these for the entire week. Use the MasterChess Opening Trainer to drill them." },
      { heading: "Week 4 — Analyze every game", body: "After every loss, open the game in the Analysis page, find your three biggest mistakes with Stockfish, and write down WHY the move was bad. Patterns will jump out by day 7." },
    ],
    faqs: [
      { q: "How long does it take to improve at chess?", a: "Most adults gain 100–200 rating points in their first 3 months of structured practice. After 1800, gains slow dramatically." },
      { q: "Should I do puzzles to improve?", a: "Tactics training helps under 1500. Above that, study annotated games and endgames — they teach pattern depth that puzzles can't." },
      { q: "How many hours a day should I study chess?", a: "30–60 focused minutes beats 4 hours of mindless blitz. Quality over quantity." },
    ],
    relatedSlugs: ["chess-rating-elo-explained", "best-chess-openings-for-beginners", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "scholars-mate",
    title: "Scholar's Mate — 4-Move Checkmate (And How to Stop It)",
    metaDescription: "Scholar's Mate explained: the 4-move checkmate, why it works, and the one defense that beats it every time. Try it on a free interactive board.",
    h1: "Scholar's Mate — The 4-Move Checkmate",
    keyword: "scholar's mate",
    intro: "Scholar's Mate is the famous 4-move checkmate every beginner falls for once. It exploits a single weak square — f7 for black, f2 for white — that is defended only by the king. Here's exactly how it works, how to deliver it, and the one move that kills it forever.",
    steps: [
      { name: "1.e4 e5", text: "Both sides claim the center." },
      { name: "2.Qh5", text: "Bring the queen out early, targeting both e5 and f7." },
      { name: "3.Bc4", text: "Aim the bishop at f7. Now f7 is attacked twice." },
      { name: "4.Qxf7#", text: "If black hasn't defended, the queen captures f7 with the bishop's support. The king has no escape." },
    ],
    sections: [
      { heading: "Why f7 is the weakest square", body: "f7 is only defended by the black king. Attack it with two pieces and a beginner who doesn't know the defense will be checkmated before move 5." },
      { heading: "How to defend against Scholar's Mate", body: "After 2.Qh5, play 2…Nc6 (defending e5) and 3…g6 (kicking the queen). The queen has to retreat and white has just wasted three moves. Black is winning." },
      { heading: "Why strong players never play it", body: "It only works against complete beginners. Above 600 ELO, the defender will kick your queen, develop with tempo, and steamroll your underdeveloped pieces. Useful as a one-time learning tool, not as an opening." },
    ],
    faqs: [
      { q: "What is the fastest checkmate in chess?", a: "Fool's Mate, in 2 moves. Scholar's Mate is 4 moves but happens way more often in real games." },
      { q: "Is Scholar's Mate cheating?", a: "No — it's a legal sequence. It's just rarely effective above absolute beginner level." },
      { q: "How do you stop Scholar's Mate?", a: "Defend e5 with …Nc6 and kick the queen with …g6. White loses tempo and the attack collapses." },
    ],
    relatedSlugs: ["fools-mate", "how-to-play-chess", "chess-opening-traps"],
    updated: "2026-05-14",
  },
  {
    slug: "fools-mate",
    title: "Fool's Mate — The Fastest Checkmate in Chess (2 Moves)",
    metaDescription: "Fool's Mate is checkmate in 2 moves — the fastest possible in chess. The exact moves, why it works, and how to never fall for it again.",
    h1: "Fool's Mate — Checkmate in Just 2 Moves",
    keyword: "fool's mate",
    intro: "Fool's Mate is the absolute fastest checkmate possible in chess: just two moves. It requires white to play perhaps the two worst opening moves on the board, and black to spot the kill. Almost no one falls for it, but it's the most famous miniature in chess history.",
    steps: [
      { name: "1.f3 (or 1.f4) — the worst opening move", text: "White weakens the diagonal to their own king and develops nothing." },
      { name: "1…e5 — black opens the center", text: "Black plays a normal move." },
      { name: "2.g4 — disaster", text: "White further weakens the king's diagonal." },
      { name: "2…Qh4#", text: "The queen lands on h4 attacking the white king. The king has no legal move — there are no pieces to block and no squares to flee. Checkmate." },
    ],
    sections: [
      { heading: "Why it works", body: "After 1.f3 and 2.g4, white has opened a fatal diagonal (e1-h4) to their own king with no defenders. The black queen exploits it on move 2 — the earliest possible checkmate." },
      { heading: "Has Fool's Mate ever happened in a real tournament?", body: "Yes — extremely rarely. There are scattered reports of titled players blundering into it under serious time pressure. It's the chess equivalent of getting hit by lightning twice." },
    ],
    faqs: [
      { q: "What is the fastest checkmate in chess?", a: "Fool's Mate in 2 moves. No checkmate is possible in 1 move from the starting position." },
      { q: "Can you checkmate in 3 moves?", a: "Yes — variations exist with 3-move forced mates, but Fool's Mate (2 moves) and Scholar's Mate (4 moves) are the famous ones." },
      { q: "Why is it called Fool's Mate?", a: "Because only a fool would play the moves white plays. It's a teaching example, not a real strategy." },
    ],
    relatedSlugs: ["scholars-mate", "stalemate-vs-checkmate", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-opening-traps",
    title: "10 Best Chess Opening Traps Every Beginner Should Know",
    metaDescription: "The 10 most useful chess opening traps: Fried Liver, Légal's Mate, Englund Gambit Trap, Lasker Trap and more. Try them all on a free board.",
    h1: "10 Best Chess Opening Traps for Beginners",
    keyword: "chess opening traps",
    intro: "Opening traps win games. The best ones aren't gimmicks — they exploit real, common mistakes. Memorize these ten and you'll catch opponents off-guard for years. Each one comes with a Stockfish-verified refutation, so you also know how to avoid falling for them.",
    sections: [
      { heading: "1. Fried Liver Attack", body: "1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 d5 5.exd5 Nxd5 6.Nxf7! Sacrifices a knight to drag the black king to the center. Devastating below 1500." },
      { heading: "2. Légal's Mate", body: "1.e4 e5 2.Nf3 d6 3.Bc4 Bg4 4.Nc3 g6 5.Nxe5! White sacrifices the queen to deliver mate in three with three minor pieces." },
      { heading: "3. Englund Gambit Trap", body: "1.d4 e5 2.dxe5 Nc6 3.Nf3 Qe7 4.Bf4? Nb4! Black wins material immediately." },
      { heading: "4. Lasker Trap (Albin Counter-Gambit)", body: "Black underpromotes to a knight to win the white queen — one of the rarest ideas in chess." },
      { heading: "5. Elephant Trap", body: "In the Queen's Gambit Declined, black sets up a piece sacrifice on move 6 that wins a piece if white grabs the bait." },
      { heading: "6. Noah's Ark Trap", body: "In the Ruy Lopez, black traps the white bishop on b3 with …a6, …b5, and …c4." },
      { heading: "7. Mortimer Trap", body: "Ruy Lopez Berlin — a knight maneuver that wins a piece if white falls for the obvious recapture." },
      { heading: "8. Blackburne Shilling Gambit", body: "1.e4 e5 2.Nf3 Nc6 3.Bc4 Nd4 — looks like a beginner mistake but contains a queen-trapping idea." },
      { heading: "9. Stafford Gambit", body: "1.e4 e5 2.Nf3 Nf6 3.Nxe5 Nc6 — extremely popular on YouTube; tons of tactical traps." },
      { heading: "10. Tennison Gambit", body: "1.e4 d5 2.Nf3 dxe4 3.Ng5 — leads to the famous Tennison-Halosar trap if black plays 3…Nf6 4.Nc3." },
    ],
    faqs: [
      { q: "Are opening traps good for improvement?", a: "Yes for fun and rating points; less for deep understanding. Use them to win, then study the underlying principles." },
      { q: "Do grandmasters fall for opening traps?", a: "Almost never the famous ones, but yes to obscure home-prep traps. The Berlin Defense itself was once considered a trap before it became mainline." },
    ],
    relatedSlugs: ["scholars-mate", "italian-game-opening", "queens-gambit-opening"],
    updated: "2026-05-14",
  },
  {
    slug: "knight-moves-chess",
    title: "Knight Moves in Chess — The L-Shape, Outposts & Tactics",
    metaDescription: "How the knight moves in chess: the L-shape pattern, when knights beat bishops, the smothered mate, and the famous knight tour. With a free trainer.",
    h1: "Knight Moves in Chess — The Complete Guide",
    keyword: "knight moves chess",
    intro: "The knight is the strangest piece in chess. It jumps over other pieces, moves in an L-shape, and is the only piece that can attack a queen without being attacked back. Mastering knights is what separates 1200 players from 1600 players.",
    sections: [
      { heading: "How the knight moves", body: "Two squares in one direction, then one square perpendicular. Or equivalently: any move that lands on a square of the opposite color, two squares away in an L. The knight ALWAYS changes square color with every move." },
      { heading: "Knights vs bishops", body: "Knights excel in closed positions (pawns blocking diagonals). Bishops excel in open positions (long open diagonals). The 'good' minor piece is determined by pawn structure, not piece value." },
      { heading: "Knight outposts", body: "An outpost is a square deep in enemy territory that can't be attacked by a pawn. A knight on an outpost on the 5th or 6th rank is worth nearly a rook." },
      { heading: "Smothered mate — the knight's signature attack", body: "When the king is boxed in by its own pieces, a knight can deliver checkmate that no other piece can block or capture. The classic pattern: Qh5+, Kf8, Nxf7#." },
      { heading: "The Knight's Tour", body: "A famous chess puzzle: move a knight to every square on the board exactly once. Solutions have existed since the 9th century." },
    ],
    faqs: [
      { q: "Can a knight jump over pieces?", a: "Yes — the only piece that can. It moves in an L and lands on the destination square regardless of what's between." },
      { q: "Is a knight worth more than a bishop?", a: "Roughly equal (both 3 points). The position decides which one is actually better in a given game." },
      { q: "How many squares can a knight attack?", a: "Up to 8 (from the center). As few as 2 from a corner — knights hate corners." },
    ],
    relatedSlugs: ["chess-piece-names-and-moves", "chess-piece-values", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "what-is-a-gambit-in-chess",
    title: "What Is a Gambit in Chess? (Plus the 7 Best Gambits)",
    metaDescription: "A gambit is a deliberate pawn sacrifice for activity. Here are the 7 best gambits — Queen's Gambit, King's, Evans, Smith-Morra, Benko, Latvian and Budapest.",
    h1: "What Is a Gambit in Chess?",
    keyword: "what is a gambit in chess",
    intro: "A gambit is a deliberate sacrifice — usually a pawn, sometimes a piece — in the opening, in exchange for faster development, central control, or a king attack. Some gambits are 100% sound; others are pure trickery. Here's the rundown.",
    sections: [
      { heading: "Sound gambits (proven over a century)", body: "Queen's Gambit (1.d4 d5 2.c4) — not really a gambit because white usually recovers the pawn. Evans Gambit (Italian Game) — Kasparov's favorite surprise weapon. Benko Gambit (1.d4 Nf6 2.c4 c5 3.d5 b5) — black gets long-term queenside pressure for a pawn." },
      { heading: "Sharp practical gambits", body: "Smith-Morra Gambit (1.e4 c5 2.d4 cxd4 3.c3) — white sacs a pawn to bypass Sicilian theory. King's Gambit (1.e4 e5 2.f4) — the most romantic gambit, dubious at master level but devastating below 1800." },
      { heading: "Risky surprise weapons", body: "Latvian Gambit (1.e4 e5 2.Nf3 f5) — almost refuted but wins many games at amateur level. Budapest Gambit (1.d4 Nf6 2.c4 e5) — solid surprise vs 1.d4." },
      { heading: "How to play a gambit well", body: "Develop everything fast. Castle early. Open lines toward the opponent's king. Don't try to recover the pawn — play for the attack. If you've played 10 moves and have no threats, the gambit failed." },
    ],
    faqs: [
      { q: "Is the Queen's Gambit a real gambit?", a: "Technically yes, but white almost always recovers the pawn within a few moves. It's a 'temporary' gambit." },
      { q: "Are gambits good for beginners?", a: "Yes! Gambits teach attacking chess, fast development, and the value of initiative — all crucial skills below 1800." },
      { q: "What is the most aggressive gambit?", a: "The King's Gambit (2.f4) for white, the Latvian Gambit (2…f5) for black. Both are wild and tactical." },
    ],
    relatedSlugs: ["queens-gambit-opening", "italian-game-opening", "best-chess-openings-for-beginners"],
    updated: "2026-05-14",
  },
  {
    slug: "best-chess-players-of-all-time",
    title: "The 10 Best Chess Players of All Time (Ranked)",
    metaDescription: "The 10 greatest chess players ever — Magnus Carlsen, Garry Kasparov, Bobby Fischer, Anatoly Karpov, José Capablanca. Peak ratings, achievements, and style.",
    h1: "The 10 Best Chess Players of All Time",
    keyword: "best chess players of all time",
    intro: "Ranking the greatest chess players ever is a perfect bar argument — strong opinions, no perfect answer. Here's a defensible top 10 based on peak rating, dominance over their era, and tournament results. Numbers from FIDE; commentary is editorial.",
    sections: [
      { heading: "1. Magnus Carlsen (Norway, 1990–)", body: "Peak rating 2882 — the highest in history. World Champion 2013–2023. Total dominance for over a decade; only Garry Kasparov rivals him for longest reign at #1." },
      { heading: "2. Garry Kasparov (Russia, 1963–)", body: "Peak rating 2851. World Champion 1985–2000. #1 in the world for 255 of 256 months. Arguably the greatest tournament player ever." },
      { heading: "3. Bobby Fischer (USA, 1943–2008)", body: "Defeated Boris Spassky in 1972 to break Soviet chess hegemony. Achieved a Performance Rating of ~3000 in his peak run. Erratic post-1972 — but undeniable peak." },
      { heading: "4. Anatoly Karpov (Russia, 1951–)", body: "World Champion 1975–1985. Played 5 epic matches against Kasparov in the 1980s. Positional genius and the strongest 1.d4 player ever." },
      { heading: "5. José Raúl Capablanca (Cuba, 1888–1942)", body: "World Champion 1921–1927. Lost only 35 serious games his entire life. Endgame technique still studied today." },
      { heading: "6. Emanuel Lasker (Germany, 1868–1941)", body: "World Champion for 27 years (1894–1921), the longest reign ever. Brilliant psychologist and fighter." },
      { heading: "7. Mikhail Botvinnik (USSR, 1911–1995)", body: "World Champion three times. Founded the Soviet chess school that dominated for 60 years." },
      { heading: "8. Viswanathan Anand (India, 1969–)", body: "World Champion 2007–2013. Lightning calculation, equally strong in all phases." },
      { heading: "9. Mikhail Tal (Latvia, 1936–1992)", body: "World Champion 1960. The 'Magician from Riga' — most beautiful attacker in history." },
      { heading: "10. Alexander Alekhine (Russia/France, 1892–1946)", body: "World Champion 1927–1935, 1937–1946. Famous for deep combinations and aggressive style." },
    ],
    faqs: [
      { q: "Who is the GOAT of chess?", a: "Magnus Carlsen by peak rating and modern dominance; Garry Kasparov by longest dominance of any era. Reasonable people disagree." },
      { q: "Is Hikaru Nakamura on this list?", a: "Hikaru is the strongest blitz/bullet player of all time but his classical peak (~2816) doesn't reach the top 10." },
      { q: "What is Magnus Carlsen's rating?", a: "His peak FIDE classical rating was 2882 in 2014 — the highest ever recorded." },
    ],
    relatedSlugs: ["chess-rating-elo-explained", "how-to-improve-at-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-strategy-for-beginners",
    title: "Chess Strategy for Beginners — 7 Principles That Work",
    metaDescription: "Chess strategy for beginners simplified: control the center, develop fast, castle early, double rooks, find weak squares. 7 rules that beat 90% of opponents.",
    h1: "Chess Strategy for Beginners — 7 Principles",
    keyword: "chess strategy for beginners",
    intro: "Chess strategy isn't about memorizing patterns — it's about a handful of timeless principles you apply every move. Master these seven and you'll beat 90% of casual opponents without ever opening a book.",
    sections: [
      { heading: "1. Control the center", body: "The four central squares (e4, d4, e5, d5) are the busiest highways on the board. Pieces in the center control more squares and can swing to either flank. Start with 1.e4 or 1.d4 and fight for these squares." },
      { heading: "2. Develop fast", body: "Knights before bishops, bishops before queen. Get every minor piece off the back rank before move 10. Players who develop fast win games before slow players finish setting up." },
      { heading: "3. Castle early", body: "Castle within the first 10 moves in 95% of games. A king in the center invites tactical disasters. Kingside castling is usually safer than queenside." },
      { heading: "4. Connect your rooks", body: "After castling, get the queen off the back rank so your rooks can defend each other on the open file. Doubled rooks on an open file are crushing." },
      { heading: "5. Find weak squares", body: "A weak square is one your opponent can't defend with a pawn. Put a knight there and it becomes a permanent thorn. Look for them every move." },
      { heading: "6. Trade when ahead in material", body: "Up a piece? Simplify. Trading queens and minor pieces reduces complications and converts your advantage into a winning endgame." },
      { heading: "7. Don't move the same piece twice in the opening", body: "Each tempo wasted on the same piece is a free move for your opponent to develop. Move a piece once, get it to a good square, leave it alone." },
    ],
    faqs: [
      { q: "What is the best chess strategy for beginners?", a: "Control the center, develop fast, castle early. These three alone beat 90% of casual opponents." },
      { q: "How do I get better at chess fast?", a: "Stop blundering: every move ask 'is anything attacked?'. Learn 5 endgame patterns. Pick one opening per color. Review every loss with Stockfish." },
      { q: "Should I attack or defend in chess?", a: "Attack when you're ahead in development; defend when you're behind. The position decides — not your mood." },
    ],
    relatedSlugs: ["how-to-improve-at-chess", "best-chess-openings-for-beginners", "how-to-play-chess"],
    updated: "2026-05-14",
  },
  {
    slug: "chess-clock-rules",
    title: "Chess Clock Rules — Bullet, Blitz, Rapid, Classical Explained",
    metaDescription: "Chess clock rules and time controls: Bullet (1+0), Blitz (3+0, 5+0), Rapid (10+0, 15+10), Classical. Increment vs delay, flagging, and the touch-move rule.",
    h1: "Chess Clock Rules — Every Time Control Explained",
    keyword: "chess clock rules",
    intro: "Time pressure is the great equalizer in chess. The world's best players blunder at 5 seconds on the clock the same way you do. Here's every time control, every clock rule, and how to pick the right format for your skill level.",
    sections: [
      { heading: "The time control formats", body: "Bullet: 1+0 or 2+1 — pure speed, almost no thinking. Blitz: 3+0 or 5+0 — fast intuition. Rapid: 10+0 or 15+10 — real chess, fast. Classical: 30+0 to 90+30 — deep thought. Each format rewards different skills." },
      { heading: "Increment vs delay", body: "Increment: clock gains X seconds AFTER your move ('Fischer'). Delay: clock waits X seconds BEFORE counting down ('Bronstein'). Increment is more forgiving and is the modern standard." },
      { heading: "Flagging", body: "When your clock hits 0:00, you lose — even if you're winning, even checkmated. Exception: if the opponent has 'insufficient material to checkmate' (e.g., lone king), the game is a draw." },
      { heading: "Touch-move rule", body: "In serious games, if you touch a piece you must move it (if it has a legal move). If you say 'I adjust' ('j'adoube') first, you can center it without committing." },
      { heading: "Which time control is best for beginners?", body: "Rapid 10+0 or 15+10. Long enough to think, short enough to play several games an hour. Bullet and blitz teach bad habits at low ratings." },
    ],
    faqs: [
      { q: "What does 5+0 mean in chess?", a: "5 minutes total time per player, 0 seconds increment per move. Pure blitz." },
      { q: "What does 15+10 mean in chess?", a: "15 minutes base + 10 seconds added after each move. Standard rapid." },
      { q: "What happens if you run out of time in chess?", a: "You lose, unless your opponent cannot checkmate you with any sequence of legal moves (e.g., they have only a king). Then it's a draw." },
    ],
    relatedSlugs: ["how-to-play-chess", "chess-rating-elo-explained"],
    updated: "2026-05-14",
  },
];

export const getArticleBySlug = (slug: string) =>
  LEARN_ARTICLES.find((a) => a.slug === slug) ?? null;
