import { type Difficulty } from "./chess-ai";

export interface OnlineBotProfile {
  id: string;
  displayName: string;
  username: string;
  rating: number;
  country: string;
  countryFlag: string;
  gamesPlayed: number;
  gamesWon: number;
  gamesLost: number;
  gamesDrawn: number;
  difficulty: Difficulty;
  avatarInitials: string;
  isOnline: boolean;
  lastSeen: string;
}

// These bots look like real players - realistic names, stats, countries
export const ONLINE_BOTS: OnlineBotProfile[] = [
  {
    id: "bot-alex-fischer",
    displayName: "Alex Fischer",
    username: "alex_fischer92",
    rating: 1450,
    country: "Germany",
    countryFlag: "🇩🇪",
    gamesPlayed: 342,
    gamesWon: 178,
    gamesLost: 140,
    gamesDrawn: 24,
    difficulty: "intermediate",
    avatarInitials: "AF",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-marko-petrovic",
    displayName: "Marko Petrović",
    username: "marko_chess",
    rating: 1280,
    country: "Serbia",
    countryFlag: "🇷🇸",
    gamesPlayed: 215,
    gamesWon: 98,
    gamesLost: 102,
    gamesDrawn: 15,
    difficulty: "intermediate",
    avatarInitials: "MP",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-elena-volkov",
    displayName: "Elena Volkov",
    username: "elena_v",
    rating: 1620,
    country: "Russia",
    countryFlag: "🇷🇺",
    gamesPlayed: 487,
    gamesWon: 268,
    gamesLost: 189,
    gamesDrawn: 30,
    difficulty: "advanced",
    avatarInitials: "EV",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-yuki-tanaka",
    displayName: "Yuki Tanaka",
    username: "yuki_t_chess",
    rating: 1100,
    country: "Japan",
    countryFlag: "🇯🇵",
    gamesPlayed: 156,
    gamesWon: 62,
    gamesLost: 80,
    gamesDrawn: 14,
    difficulty: "beginner",
    avatarInitials: "YT",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-carlos-martinez",
    displayName: "Carlos Martinez",
    username: "carlos_gm",
    rating: 1750,
    country: "Spain",
    countryFlag: "🇪🇸",
    gamesPlayed: 612,
    gamesWon: 380,
    gamesLost: 198,
    gamesDrawn: 34,
    difficulty: "advanced",
    avatarInitials: "CM",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-sophie-laurent",
    displayName: "Sophie Laurent",
    username: "sophie_l",
    rating: 980,
    country: "France",
    countryFlag: "🇫🇷",
    gamesPlayed: 89,
    gamesWon: 28,
    gamesLost: 52,
    gamesDrawn: 9,
    difficulty: "beginner",
    avatarInitials: "SL",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-nikola-jovanovic",
    displayName: "Nikola Jovanović",
    username: "niko_chess64",
    rating: 1340,
    country: "Serbia",
    countryFlag: "🇷🇸",
    gamesPlayed: 278,
    gamesWon: 134,
    gamesLost: 126,
    gamesDrawn: 18,
    difficulty: "intermediate",
    avatarInitials: "NJ",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-liam-obrien",
    displayName: "Liam O'Brien",
    username: "liam_ob",
    rating: 1550,
    country: "Ireland",
    countryFlag: "🇮🇪",
    gamesPlayed: 405,
    gamesWon: 218,
    gamesLost: 162,
    gamesDrawn: 25,
    difficulty: "advanced",
    avatarInitials: "LO",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-aisha-khan",
    displayName: "Aisha Khan",
    username: "aisha_k",
    rating: 1420,
    country: "Pakistan",
    countryFlag: "🇵🇰",
    gamesPlayed: 310,
    gamesWon: 155,
    gamesLost: 135,
    gamesDrawn: 20,
    difficulty: "intermediate",
    avatarInitials: "AK",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-viktor-petrov",
    displayName: "Viktor Petrov",
    username: "viktor_p",
    rating: 1680,
    country: "Bulgaria",
    countryFlag: "🇧🇬",
    gamesPlayed: 530,
    gamesWon: 302,
    gamesLost: 196,
    gamesDrawn: 32,
    difficulty: "advanced",
    avatarInitials: "VP",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-mei-zhang",
    displayName: "Mei Zhang",
    username: "mei_zh",
    rating: 1200,
    country: "China",
    countryFlag: "🇨🇳",
    gamesPlayed: 180,
    gamesWon: 78,
    gamesLost: 88,
    gamesDrawn: 14,
    difficulty: "intermediate",
    avatarInitials: "MZ",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-stefan-mueller",
    displayName: "Stefan Müller",
    username: "stefan_m",
    rating: 1380,
    country: "Austria",
    countryFlag: "🇦🇹",
    gamesPlayed: 295,
    gamesWon: 142,
    gamesLost: 133,
    gamesDrawn: 20,
    difficulty: "intermediate",
    avatarInitials: "SM",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-isabella-rossi",
    displayName: "Isabella Rossi",
    username: "bella_chess",
    rating: 1050,
    country: "Italy",
    countryFlag: "🇮🇹",
    gamesPlayed: 120,
    gamesWon: 45,
    gamesLost: 65,
    gamesDrawn: 10,
    difficulty: "beginner",
    avatarInitials: "IR",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-david-kim",
    displayName: "David Kim",
    username: "david_k_gm",
    rating: 1900,
    country: "South Korea",
    countryFlag: "🇰🇷",
    gamesPlayed: 780,
    gamesWon: 498,
    gamesLost: 240,
    gamesDrawn: 42,
    difficulty: "advanced",
    avatarInitials: "DK",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-ana-popescu",
    displayName: "Ana Popescu",
    username: "ana_pop",
    rating: 1150,
    country: "Romania",
    countryFlag: "🇷🇴",
    gamesPlayed: 165,
    gamesWon: 68,
    gamesLost: 82,
    gamesDrawn: 15,
    difficulty: "beginner",
    avatarInitials: "AP",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-james-wilson",
    displayName: "James Wilson",
    username: "j_wilson99",
    rating: 1500,
    country: "United States",
    countryFlag: "🇺🇸",
    gamesPlayed: 365,
    gamesWon: 185,
    gamesLost: 158,
    gamesDrawn: 22,
    difficulty: "intermediate",
    avatarInitials: "JW",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-katarina-ilic",
    displayName: "Katarina Ilić",
    username: "kata_chess",
    rating: 1320,
    country: "Serbia",
    countryFlag: "🇷🇸",
    gamesPlayed: 248,
    gamesWon: 118,
    gamesLost: 112,
    gamesDrawn: 18,
    difficulty: "intermediate",
    avatarInitials: "KI",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-mohammed-rashid",
    displayName: "Mohammed Al-Rashid",
    username: "mo_rashid",
    rating: 1580,
    country: "UAE",
    countryFlag: "🇦🇪",
    gamesPlayed: 420,
    gamesWon: 230,
    gamesLost: 165,
    gamesDrawn: 25,
    difficulty: "advanced",
    avatarInitials: "MR",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-emma-andersson",
    displayName: "Emma Andersson",
    username: "emma_a",
    rating: 1260,
    country: "Sweden",
    countryFlag: "🇸🇪",
    gamesPlayed: 200,
    gamesWon: 90,
    gamesLost: 96,
    gamesDrawn: 14,
    difficulty: "intermediate",
    avatarInitials: "EA",
    isOnline: true,
    lastSeen: "now",
  },
  {
    id: "bot-raj-patel",
    displayName: "Raj Patel",
    username: "raj_chess",
    rating: 1440,
    country: "India",
    countryFlag: "🇮🇳",
    gamesPlayed: 330,
    gamesWon: 168,
    gamesLost: 140,
    gamesDrawn: 22,
    difficulty: "intermediate",
    avatarInitials: "RP",
    isOnline: true,
    lastSeen: "now",
  },
];

// Pick a bot close to the player's rating
export function matchBot(playerRating: number): OnlineBotProfile {
  const sorted = [...ONLINE_BOTS].sort(
    (a, b) => Math.abs(a.rating - playerRating) - Math.abs(b.rating - playerRating)
  );
  // Pick from top 5 closest, randomly
  const pool = sorted.slice(0, 5);
  return pool[Math.floor(Math.random() * pool.length)];
}

// Get random subset of "online" bots for display
export function getOnlineBots(count: number = 8): OnlineBotProfile[] {
  const shuffled = [...ONLINE_BOTS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// Get difficulty based on rating
export function getDifficultyForRating(rating: number): Difficulty {
  if (rating < 1100) return "beginner";
  if (rating < 1500) return "intermediate";
  return "advanced";
}
