export interface Puzzle {
  fen: string;
  playerColor: "w" | "b";
  moves: string[];
  title: string;
  hint: string;
  answer: string;
  difficulty: "easy" | "medium" | "hard";
  mateIn: number;
  category?: string;
  premium?: boolean;
}

export const PUZZLES: Puzzle[] = [
  // Free set
  {
    fen: "k7/1Q6/2K5/8/8/8/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Qb8#"],
    title: "Corner Queen Mate A",
    hint: "Use the queen with king support.",
    answer: "1. Qb8#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "7k/6Q1/5K2/8/8/8/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Qg8#"],
    title: "Corner Queen Mate B",
    hint: "The king supports g8.",
    answer: "1. Qg8#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "8/8/8/8/8/8/1QK5/k7 w - - 0 1",
    playerColor: "w",
    moves: ["Qb1#"],
    title: "Corner Queen Mate C",
    hint: "Mate on b1.",
    answer: "1. Qb1#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "8/8/8/8/8/8/5KQ1/7k w - - 0 1",
    playerColor: "w",
    moves: ["Qg1#"],
    title: "Corner Queen Mate D",
    hint: "Queen to g1 is mate.",
    answer: "1. Qg1#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "k7/8/1K6/8/8/8/8/7R w - - 0 1",
    playerColor: "w",
    moves: ["Rh8#"],
    title: "Rook Mate A",
    hint: "Rook to the 8th rank.",
    answer: "1. Rh8#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "7k/8/6K1/8/8/8/8/R7 w - - 0 1",
    playerColor: "w",
    moves: ["Ra8#"],
    title: "Rook Mate B",
    hint: "Rook to a8.",
    answer: "1. Ra8#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "7R/8/8/8/8/8/1K6/k7 w - - 0 1",
    playerColor: "w",
    moves: ["Rh1#"],
    title: "Rook Mate C",
    hint: "Drop to the first rank.",
    answer: "1. Rh1#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "R7/8/8/8/8/8/6K1/7k w - - 0 1",
    playerColor: "w",
    moves: ["Ra1#"],
    title: "Rook Mate D",
    hint: "Mate on a1.",
    answer: "1. Ra1#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "k7/8/1QK5/8/8/8/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Qb8#"],
    title: "Queen Lift Mate A",
    hint: "Lift the queen to b8.",
    answer: "1. Qb8#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "7k/8/5KQ1/8/8/8/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Qg8#"],
    title: "Queen Lift Mate B",
    hint: "Lift the queen to g8.",
    answer: "1. Qg8#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "8/8/8/8/8/1Q6/2K5/k7 w - - 0 1",
    playerColor: "w",
    moves: ["Qb1#"],
    title: "Queen Lift Mate C",
    hint: "Lift the queen to b1.",
    answer: "1. Qb1#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },
  {
    fen: "8/8/8/8/8/6Q1/5K2/7k w - - 0 1",
    playerColor: "w",
    moves: ["Qg1#"],
    title: "Queen Lift Mate D",
    hint: "Lift the queen to g1.",
    answer: "1. Qg1#",
    difficulty: "easy",
    mateIn: 1,
    category: "checkmate",
  },

  // Premium set
  {
    fen: "k7/1K6/8/8/8/7R/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Rh8#"],
    title: "Rook Swing Mate A",
    hint: "Swing rook to h8.",
    answer: "1. Rh8#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "6k1/6K1/8/8/8/R7/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Ra8#"],
    title: "Rook Swing Mate B",
    hint: "Swing rook to a8.",
    answer: "1. Ra8#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "8/8/8/8/8/7R/1K6/k7 w - - 0 1",
    playerColor: "w",
    moves: ["Rh1#"],
    title: "Rook Swing Mate C",
    hint: "Swing rook to h1.",
    answer: "1. Rh1#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "8/8/8/8/8/R7/6K1/7k w - - 0 1",
    playerColor: "w",
    moves: ["Ra1#"],
    title: "Rook Swing Mate D",
    hint: "Swing rook to a1.",
    answer: "1. Ra1#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    playerColor: "w",
    moves: ["Qxf7#"],
    title: "Scholar's Mate",
    hint: "Attack f7.",
    answer: "1. Qxf7#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "opening",
  },
  {
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    playerColor: "w",
    moves: ["Re8#"],
    title: "Back Rank Classic",
    hint: "Back-rank weakness.",
    answer: "1. Re8#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "3r2k1/8/8/8/8/8/5PPP/6K1 b - - 0 1",
    playerColor: "b",
    moves: ["Rd1#"],
    title: "Black Back Rank",
    hint: "White king is boxed in.",
    answer: "1...Rd1#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "7k/5Q1p/8/8/8/8/8/6K1 w - - 0 1",
    playerColor: "w",
    moves: ["Qg8#"],
    title: "Queen Corner Trap",
    hint: "Mate in the corner.",
    answer: "1. Qg8#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "5k2/5P2/5K2/8/8/8/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["f8=Q#"],
    title: "Promotion Mate",
    hint: "Promote with mate.",
    answer: "1. f8=Q#",
    difficulty: "hard",
    mateIn: 1,
    premium: true,
    category: "endgame",
  },
  {
    fen: "7k/R7/6K1/8/8/8/8/8 w - - 0 1",
    playerColor: "w",
    moves: ["Ra8#"],
    title: "Ladder Mate",
    hint: "Rook to a8.",
    answer: "1. Ra8#",
    difficulty: "medium",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "k7/p7/1K6/8/8/8/8/3R4 w - - 0 1",
    playerColor: "w",
    moves: ["Rd8#"],
    title: "Corridor Mate",
    hint: "Rook to d8.",
    answer: "1. Rd8#",
    difficulty: "hard",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
  {
    fen: "7k/8/8/6N1/8/8/8/6RK w - - 0 1",
    playerColor: "w",
    moves: ["Rg8#"],
    title: "Arabian Mate",
    hint: "Rook and knight coordination.",
    answer: "1. Rg8#",
    difficulty: "hard",
    mateIn: 1,
    premium: true,
    category: "checkmate",
  },
];

export const PUZZLE_CATEGORIES = [...new Set(PUZZLES.map((p) => p.category).filter(Boolean))];
export const FREE_PUZZLES = PUZZLES.filter((p) => !p.premium);
export const PREMIUM_PUZZLES = PUZZLES.filter((p) => p.premium);
