import { type Difficulty } from "../chess-ai";
import type { Playstyle, OpeningRepertoire } from "./playstyles";

export interface BotProfile {
  id: string;
  name: string;
  avatar: string;
  rating: number;
  difficulty: Difficulty;
  personality: string;
  /** How the bot picks moves: aggressive, positional, etc. */
  playstyle: Playstyle;
  /** Preferred opening systems — bot will try to follow these. */
  openings: OpeningRepertoire[];
  /** 0..1 — chance the bot plays the engine-best move. Lower = more human. */
  accuracy: number;
  /** 0..1 — chance per move the bot blunders (drops material / misses tactic). */
  blunderRate: number;
  /** 0..1 — chance per move the bot makes a small inaccuracy. */
  inaccuracyRate: number;
  /** How many plies of opening theory the bot will follow before going its own way. */
  bookDepth: number;
  country: string;
  countryFlag: string;
  style: string;
  bio: string;
  drawAcceptThreshold: number;
  resignThreshold: number;
  taunts: {
    greeting: string;
    onCheck: string;
    onCapture: string;
    onBlunder: string;
    onWin: string;
    onLose: string;
    onDraw: string;
    onDrawOffer: string;
    onDrawDecline: string;
  };
}

export const BOT_PROFILES: BotProfile[] = [
  // ===== 👑 MASTERCHESS — THE UNBEATABLE BOSS BOT =====
  // Pure Stockfish at maximum strength. No blunders, no inaccuracies, full opening prep.
  // Engine settings give this bot uncapped UCI strength + max depth/time (see bot-engine.ts).
  {
    id: "masterchess",
    name: "MasterChess",
    avatar: "👑",
    rating: 3200,
    difficulty: "master",
    personality: "unbeatable",
    playstyle: "universal",
    openings: ["ruy-lopez", "queens-gambit", "sicilian", "english", "caro-kann", "kings-indian", "french", "italian"],
    accuracy: 1.0,
    blunderRate: 0,
    inaccuracyRate: 0,
    bookDepth: 30,
    country: "MasterChess",
    countryFlag: "👑",
    style: "Engine-perfect — no human can win",
    bio: "The final boss of MasterChess. Plays at superhuman strength with zero mistakes. Defeating it is considered impossible.",
    drawAcceptThreshold: 120,
    resignThreshold: 50,
    taunts: {
      greeting: "I am MasterChess. Few have drawn. None have won. 👑",
      onCheck: "Check. The end is already calculated.",
      onCapture: "Every exchange is a step toward inevitability.",
      onBlunder: "...this should not happen.",
      onWin: "As foreseen. 👑",
      onLose: "Impossible. You have made history.",
      onDraw: "A rare and respectable result.",
      onDrawOffer: "A draw against me is a victory. Accepted.",
      onDrawDecline: "The position still favors precision.",
    },
  },

  {
    id: "rookie-rosa",
    name: "Rookie Rosa",
    avatar: "🌷",
    rating: 500,
    difficulty: "beginner",
    personality: "friendly",
    playstyle: "universal",
    openings: ["italian", "scandinavian"],
    accuracy: 0.45,
    blunderRate: 0.18,
    inaccuracyRate: 0.30,
    bookDepth: 4,
    country: "Portugal",
    countryFlag: "🇵🇹",
    style: "Simple, cheerful play",
    bio: "Just learning — every game is a new adventure.",
    drawAcceptThreshold: 16,
    resignThreshold: 9999,
    taunts: {
      greeting: "Hi! Let's have fun 🌷",
      onCheck: "Oh! Already check? 😅",
      onCapture: "Got one!",
      onBlunder: "Oops, I dropped that 😵",
      onWin: "Yay, I won! 🌷",
      onLose: "Good game — I'm learning 📚",
      onDraw: "A draw works for me 🤝",
      onDrawOffer: "Sure, draw sounds good 🤝",
      onDrawDecline: "Let's keep going 😊",
    },
  },
  {
    id: "pawn-pablo",
    name: "Pawn Pablo",
    avatar: "🌵",
    rating: 800,
    difficulty: "beginner",
    personality: "curious",
    playstyle: "gambit",
    openings: ["kings-gambit", "italian", "scandinavian"],
    accuracy: 0.55,
    blunderRate: 0.13,
    inaccuracyRate: 0.25,
    bookDepth: 6,
    country: "Mexico",
    countryFlag: "🇲🇽",
    style: "Loves pushing pawns",
    bio: "Believes every pawn deserves a chance to shine.",
    drawAcceptThreshold: 22,
    resignThreshold: 5500,
    taunts: {
      greeting: "Vamos! Let's play 🌵",
      onCheck: "Check! Did you see that? 😎",
      onCapture: "Mine now!",
      onBlunder: "Hmm, that wasn't great 😬",
      onWin: "What a game! 🌵",
      onLose: "You played well — GG 🤝",
      onDraw: "Fair enough — draw 🤝",
      onDrawOffer: "Sí, draw accepted 👍",
      onDrawDecline: "Not yet — still fighting!",
    },
  },
  {
    id: "tactic-tanvi",
    name: "Tactic Tanvi",
    avatar: "⚡",
    rating: 1150,
    difficulty: "intermediate",
    personality: "sharp",
    playstyle: "tactical",
    openings: ["sicilian", "italian", "scandinavian"],
    accuracy: 0.68,
    blunderRate: 0.07,
    inaccuracyRate: 0.18,
    bookDepth: 8,
    country: "India",
    countryFlag: "🇮🇳",
    style: "Always hunting for forks and pins",
    bio: "If something's loose, Tanvi spots it.",
    drawAcceptThreshold: 32,
    resignThreshold: 2400,
    taunts: {
      greeting: "Defend your pieces ⚡",
      onCheck: "Check — tactics first.",
      onCapture: "Hanging piece, gone ⚡",
      onBlunder: "Missed that one...",
      onWin: "Clean tactic, clean win ⚡",
      onLose: "You calculated better 🤝",
      onDraw: "Neither cracked. Draw.",
      onDrawOffer: "Equal — draw accepted.",
      onDrawDecline: "Still tactical chances ⚡",
    },
  },
  {
    id: "calm-camille",
    name: "Calm Camille",
    avatar: "🕊️",
    rating: 1400,
    difficulty: "intermediate",
    personality: "positional",
    playstyle: "positional",
    openings: ["french", "london", "queens-gambit"],
    accuracy: 0.74,
    blunderRate: 0.05,
    inaccuracyRate: 0.15,
    bookDepth: 10,
    country: "France",
    countryFlag: "🇫🇷",
    style: "Smooth development, plays for squares",
    bio: "Prefers harmony and long-term pressure.",
    drawAcceptThreshold: 38,
    resignThreshold: 2100,
    taunts: {
      greeting: "Bonjour — let's play 🕊️",
      onCheck: "A quiet check still stings.",
      onCapture: "Improving the position.",
      onBlunder: "That diagonal slipped...",
      onWin: "Position over panic 🕊️",
      onLose: "Well handled 🤝",
      onDraw: "A fair draw.",
      onDrawOffer: "Level — draw accepted.",
      onDrawDecline: "Not yet, there's still play.",
    },
  },
  {
    id: "counter-kira",
    name: "Counter Kira",
    avatar: "🦂",
    rating: 1700,
    difficulty: "advanced",
    personality: "resourceful",
    playstyle: "defensive",
    openings: ["caro-kann", "french", "kings-indian"],
    accuracy: 0.82,
    blunderRate: 0.025,
    inaccuracyRate: 0.10,
    bookDepth: 12,
    country: "Japan",
    countryFlag: "🇯🇵",
    style: "Defends, then strikes back",
    bio: "Happy to absorb pressure for one big counterpunch.",
    drawAcceptThreshold: 44,
    resignThreshold: 1700,
    taunts: {
      greeting: "Push if you want — I hit back 🦂",
      onCheck: "Counterplay with check.",
      onCapture: "That was the turning point.",
      onBlunder: "Too loose. I know better.",
      onWin: "One mistake was enough 🦂",
      onLose: "Your attack held 🤝",
      onDraw: "Pressure met resistance.",
      onDrawOffer: "Equality — accepted.",
      onDrawDecline: "Still tension to play 🦂",
    },
  },
  {
    id: "fortress-felix",
    name: "Fortress Felix",
    avatar: "🧱",
    rating: 1950,
    difficulty: "advanced",
    personality: "solid",
    playstyle: "defensive",
    openings: ["caro-kann", "london", "queens-gambit"],
    accuracy: 0.87,
    blunderRate: 0.015,
    inaccuracyRate: 0.08,
    bookDepth: 14,
    country: "Germany",
    countryFlag: "🇩🇪",
    style: "Compact defense, accurate endgames",
    bio: "Very hard to break down once set up.",
    drawAcceptThreshold: 52,
    resignThreshold: 1400,
    taunts: {
      greeting: "Earn every inch 🧱",
      onCheck: "A direct question for your king.",
      onCapture: "Structure first.",
      onBlunder: "Beneath my standard.",
      onWin: "The wall held 🧱",
      onLose: "Strong conversion 🤝",
      onDraw: "No weaknesses, no winner.",
      onDrawOffer: "Stable — accepted.",
      onDrawDecline: "Position still has life.",
    },
  },
  {
    id: "endgame-eito",
    name: "Endgame Eito",
    avatar: "🎯",
    rating: 2200,
    difficulty: "expert",
    personality: "clinical",
    playstyle: "positional",
    openings: ["english", "queens-gambit", "ruy-lopez"],
    accuracy: 0.92,
    blunderRate: 0.008,
    inaccuracyRate: 0.05,
    bookDepth: 16,
    country: "South Korea",
    countryFlag: "🇰🇷",
    style: "Simplifies into winning endings",
    bio: "Thrives when every tempo matters.",
    drawAcceptThreshold: 60,
    resignThreshold: 1000,
    taunts: {
      greeting: "Trade pieces — I like my chances 🎯",
      onCheck: "A useful check.",
      onCapture: "Reducing to clean play.",
      onBlunder: "Rare miss. Noted.",
      onWin: "Technique did the rest 🎯",
      onLose: "You outplayed the ending 🤝",
      onDraw: "Exact enough.",
      onDrawOffer: "Level endgame — accepted.",
      onDrawDecline: "More to squeeze here.",
    },
  },
  {
    id: "attack-amara",
    name: "Attack Amara",
    avatar: "🔥",
    rating: 2350,
    difficulty: "expert",
    personality: "aggressive",
    playstyle: "aggressive",
    openings: ["sicilian", "kings-indian", "kings-gambit"],
    accuracy: 0.93,
    blunderRate: 0.006,
    inaccuracyRate: 0.04,
    bookDepth: 16,
    country: "Nigeria",
    countryFlag: "🇳🇬",
    style: "Initiative-heavy attacker",
    bio: "If your king feels airy, Amara is coming.",
    drawAcceptThreshold: 62,
    resignThreshold: 900,
    taunts: {
      greeting: "Let's not make this quiet 🔥",
      onCheck: "Check — more is coming.",
      onCapture: "Open lines — exactly what I wanted.",
      onBlunder: "Too much fire, not enough control.",
      onWin: "Attack converted 🔥",
      onLose: "You defended everything 🤝",
      onDraw: "Attack burned out.",
      onDrawOffer: "No breakthrough today.",
      onDrawDecline: "I still smell the king 🔥",
    },
  },
  {
    id: "gm-nova",
    name: "GM Nova",
    avatar: "🌌",
    rating: 2650,
    difficulty: "master",
    personality: "universal",
    playstyle: "universal",
    openings: ["ruy-lopez", "queens-gambit", "english", "sicilian"],
    accuracy: 0.96,
    blunderRate: 0.002,
    inaccuracyRate: 0.025,
    bookDepth: 20,
    country: "Argentina",
    countryFlag: "🇦🇷",
    style: "Universal grandmaster play",
    bio: "Comfortable in every phase, very few weaknesses.",
    drawAcceptThreshold: 74,
    resignThreshold: 700,
    taunts: {
      greeting: "Let's see how long you hold 🌌",
      onCheck: "A precise check.",
      onCapture: "All calculated.",
      onBlunder: "A rare inaccuracy.",
      onWin: "Pressure became inevitability 🌌",
      onLose: "Excellent game 🤝",
      onDraw: "Accurate from both sides.",
      onDrawOffer: "Correct result — accepted.",
      onDrawDecline: "Practical chances remain.",
    },
  },

  // ===== EXTRA BEGINNERS (400 - 999) =====
  {
    id: "newbie-nina",
    name: "Newbie Nina",
    avatar: "🐣",
    rating: 420,
    difficulty: "beginner",
    personality: "friendly",
    playstyle: "universal",
    openings: ["italian"],
    accuracy: 0.32, blunderRate: 0.28, inaccuracyRate: 0.35, bookDepth: 2,
    country: "Brazil", countryFlag: "🇧🇷",
    style: "Just learning the pieces", bio: "First games — be gentle!",
    drawAcceptThreshold: 12, resignThreshold: 9999,
    taunts: {
      greeting: "Hi! I'm new 🐣", onCheck: "Wait, that's check?", onCapture: "I took one!",
      onBlunder: "Oh no...", onWin: "I won?! 🎉", onLose: "GG, you're good!",
      onDraw: "A tie!", onDrawOffer: "OK, draw!", onDrawDecline: "Let me try more.",
    },
  },
  {
    id: "casual-cody",
    name: "Casual Cody",
    avatar: "🎲",
    rating: 650,
    difficulty: "beginner",
    personality: "relaxed",
    playstyle: "universal",
    openings: ["italian", "scandinavian"],
    accuracy: 0.40, blunderRate: 0.22, inaccuracyRate: 0.32, bookDepth: 3,
    country: "Canada", countryFlag: "🇨🇦",
    style: "Plays for fun", bio: "Chess on the weekends, no pressure.",
    drawAcceptThreshold: 14, resignThreshold: 9999,
    taunts: {
      greeting: "Hey, let's play 🎲", onCheck: "Heads up!", onCapture: "Mine.",
      onBlunder: "Whoops.", onWin: "Nice game!", onLose: "Well played!",
      onDraw: "Even split.", onDrawOffer: "Sure.", onDrawDecline: "One more try.",
    },
  },
  {
    id: "knight-noor",
    name: "Knight Noor",
    avatar: "🐴",
    rating: 950,
    difficulty: "beginner",
    personality: "curious",
    playstyle: "tactical",
    openings: ["italian", "scandinavian"],
    accuracy: 0.58, blunderRate: 0.12, inaccuracyRate: 0.24, bookDepth: 6,
    country: "Egypt", countryFlag: "🇪🇬",
    style: "Loves knight forks", bio: "Knights are the coolest piece, period.",
    drawAcceptThreshold: 24, resignThreshold: 4500,
    taunts: {
      greeting: "Watch the knights 🐴", onCheck: "Check by horse!", onCapture: "Forked!",
      onBlunder: "Too eager.", onWin: "Knights win!", onLose: "Nicely played.",
      onDraw: "Draw it is.", onDrawOffer: "Accepted.", onDrawDecline: "Still riding.",
    },
  },

  // ===== EXTRA INTERMEDIATE (1100 - 1599) =====
  {
    id: "patient-petar",
    name: "Patient Petar",
    avatar: "🌊",
    rating: 1250,
    difficulty: "intermediate",
    personality: "calm",
    playstyle: "positional",
    openings: ["london", "caro-kann"],
    accuracy: 0.70, blunderRate: 0.06, inaccuracyRate: 0.17, bookDepth: 8,
    country: "Serbia", countryFlag: "🇷🇸",
    style: "Slow strangulation", bio: "No need to rush — pieces speak.",
    drawAcceptThreshold: 34, resignThreshold: 2200,
    taunts: {
      greeting: "Polako, polako 🌊", onCheck: "Calm check.", onCapture: "Quiet trade.",
      onBlunder: "An oversight.", onWin: "Patience pays.", onLose: "Well outplayed.",
      onDraw: "Balanced.", onDrawOffer: "Accepted.", onDrawDecline: "Some life left.",
    },
  },
  {
    id: "swift-sasha",
    name: "Swift Sasha",
    avatar: "🦊",
    rating: 1350,
    difficulty: "intermediate",
    personality: "quick",
    playstyle: "tactical",
    openings: ["sicilian", "kings-gambit"],
    accuracy: 0.72, blunderRate: 0.06, inaccuracyRate: 0.16, bookDepth: 9,
    country: "Russia", countryFlag: "🇷🇺",
    style: "Fast, sharp blitz player", bio: "Time is a weapon.",
    drawAcceptThreshold: 36, resignThreshold: 2100,
    taunts: {
      greeting: "Don't blink 🦊", onCheck: "Snap check.", onCapture: "Quick grab.",
      onBlunder: "Premove disaster.", onWin: "Too fast for you.", onLose: "Sharp game.",
      onDraw: "Fair speed.", onDrawOffer: "Accepted.", onDrawDecline: "Clock's ticking.",
    },
  },
  {
    id: "scholar-soren",
    name: "Scholar Søren",
    avatar: "📘",
    rating: 1500,
    difficulty: "intermediate",
    personality: "studious",
    playstyle: "positional",
    openings: ["queens-gambit", "english", "ruy-lopez"],
    accuracy: 0.76, blunderRate: 0.04, inaccuracyRate: 0.13, bookDepth: 12,
    country: "Denmark", countryFlag: "🇩🇰",
    style: "Theory-driven mainlines", bio: "Knows his books cover to cover.",
    drawAcceptThreshold: 40, resignThreshold: 1900,
    taunts: {
      greeting: "Let's follow theory 📘", onCheck: "Standard check.", onCapture: "Book trade.",
      onBlunder: "Off-script error.", onWin: "Preparation matters.", onLose: "Excellent novelty.",
      onDraw: "Theoretical draw.", onDrawOffer: "Accepted.", onDrawDecline: "More theory ahead.",
    },
  },

  // ===== EXTRA ADVANCED (1600 - 2099) =====
  {
    id: "viktor-vex",
    name: "Viktor Vex",
    avatar: "♞",
    rating: 1650,
    difficulty: "advanced",
    personality: "tricky",
    playstyle: "tactical",
    openings: ["sicilian", "kings-indian"],
    accuracy: 0.80, blunderRate: 0.03, inaccuracyRate: 0.11, bookDepth: 12,
    country: "Bulgaria", countryFlag: "🇧🇬",
    style: "Sets traps everywhere", bio: "Every quiet move hides a threat.",
    drawAcceptThreshold: 42, resignThreshold: 1800,
    taunts: {
      greeting: "Watch every square ♞", onCheck: "Trap sprung.", onCapture: "You missed it.",
      onBlunder: "I overplayed.", onWin: "Tactics decided.", onLose: "Outcalculated.",
      onDraw: "Both sharp.", onDrawOffer: "Accepted.", onDrawDecline: "Still hidden ideas.",
    },
  },
  {
    id: "iron-ingrid",
    name: "Iron Ingrid",
    avatar: "⚔️",
    rating: 1820,
    difficulty: "advanced",
    personality: "tough",
    playstyle: "aggressive",
    openings: ["sicilian", "kings-gambit", "kings-indian"],
    accuracy: 0.84, blunderRate: 0.022, inaccuracyRate: 0.09, bookDepth: 13,
    country: "Sweden", countryFlag: "🇸🇪",
    style: "Direct, attacking chess", bio: "Trades comfort for initiative.",
    drawAcceptThreshold: 46, resignThreshold: 1600,
    taunts: {
      greeting: "Bring your shield ⚔️", onCheck: "Direct check.", onCapture: "Forward.",
      onBlunder: "Too greedy.", onWin: "Pressure broke through.", onLose: "Solid defense.",
      onDraw: "No breakthrough.", onDrawOffer: "Accepted.", onDrawDecline: "Still pushing.",
    },
  },
  {
    id: "smooth-samir",
    name: "Smooth Samir",
    avatar: "🎩",
    rating: 2050,
    difficulty: "advanced",
    personality: "elegant",
    playstyle: "positional",
    openings: ["english", "queens-gambit", "ruy-lopez"],
    accuracy: 0.89, blunderRate: 0.012, inaccuracyRate: 0.07, bookDepth: 15,
    country: "Morocco", countryFlag: "🇲🇦",
    style: "Subtle, elegant maneuvering", bio: "Wins without ever shouting.",
    drawAcceptThreshold: 54, resignThreshold: 1300,
    taunts: {
      greeting: "Shall we begin? 🎩", onCheck: "Polite check.", onCapture: "If you insist.",
      onBlunder: "Indelicate.", onWin: "As expected.", onLose: "Bravo.",
      onDraw: "Mutual respect.", onDrawOffer: "Accepted.", onDrawDecline: "Nuance remains.",
    },
  },

  // ===== EXTRA EXPERT (2100 - 2399) =====
  {
    id: "candidate-cyrus",
    name: "Candidate Cyrus",
    avatar: "🛡️",
    rating: 2150,
    difficulty: "expert",
    personality: "principled",
    playstyle: "universal",
    openings: ["ruy-lopez", "queens-gambit", "english"],
    accuracy: 0.91, blunderRate: 0.009, inaccuracyRate: 0.055, bookDepth: 16,
    country: "Iran", countryFlag: "🇮🇷",
    style: "Rounded candidate-master play", bio: "Few weaknesses, deep prep.",
    drawAcceptThreshold: 58, resignThreshold: 1100,
    taunts: {
      greeting: "Let's play a real game 🛡️", onCheck: "Precise check.", onCapture: "Clean.",
      onBlunder: "Below standard.", onWin: "Solid victory.", onLose: "Strong play.",
      onDraw: "Equal throughout.", onDrawOffer: "Accepted.", onDrawDecline: "Slight edge remains.",
    },
  },
  {
    id: "fm-fatima",
    name: "FM Fatima",
    avatar: "♛",
    rating: 2280,
    difficulty: "expert",
    personality: "refined",
    playstyle: "positional",
    openings: ["queens-gambit", "english", "caro-kann"],
    accuracy: 0.93, blunderRate: 0.006, inaccuracyRate: 0.045, bookDepth: 17,
    country: "Pakistan", countryFlag: "🇵🇰",
    style: "FIDE Master technique", bio: "Trains daily, plays cleanly.",
    drawAcceptThreshold: 62, resignThreshold: 1000,
    taunts: {
      greeting: "Good luck ♛", onCheck: "A focused check.", onCapture: "Necessary.",
      onBlunder: "Rare misstep.", onWin: "Technique held.", onLose: "Excellent play.",
      onDraw: "Correct result.", onDrawOffer: "Accepted.", onDrawDecline: "Still chances.",
    },
  },

  // ===== EXTRA MASTER / IM / GM LEVEL (2400 - 2799) =====
  {
    id: "im-ilya",
    name: "IM Ilya",
    avatar: "🎖️",
    rating: 2450,
    difficulty: "master",
    personality: "professional",
    playstyle: "universal",
    openings: ["ruy-lopez", "sicilian", "queens-gambit"],
    accuracy: 0.94, blunderRate: 0.004, inaccuracyRate: 0.035, bookDepth: 18,
    country: "Ukraine", countryFlag: "🇺🇦",
    style: "International Master strength", bio: "Solid in every position.",
    drawAcceptThreshold: 66, resignThreshold: 900,
    taunts: {
      greeting: "Let's have a serious game 🎖️", onCheck: "Sharp check.", onCapture: "Calculated.",
      onBlunder: "Disappointing.", onWin: "Convincing.", onLose: "Well played.",
      onDraw: "Balanced game.", onDrawOffer: "Accepted.", onDrawDecline: "Position has resources.",
    },
  },
  {
    id: "gm-galina",
    name: "GM Galina",
    avatar: "♜",
    rating: 2550,
    difficulty: "master",
    personality: "ruthless",
    playstyle: "aggressive",
    openings: ["sicilian", "kings-indian", "ruy-lopez"],
    accuracy: 0.95, blunderRate: 0.003, inaccuracyRate: 0.03, bookDepth: 19,
    country: "Russia", countryFlag: "🇷🇺",
    style: "Aggressive grandmaster", bio: "Hunts kings for breakfast.",
    drawAcceptThreshold: 70, resignThreshold: 800,
    taunts: {
      greeting: "Defend everything ♜", onCheck: "Pressure check.", onCapture: "Material flowing.",
      onBlunder: "Annoying slip.", onWin: "Attack converted.", onLose: "Tough defense.",
      onDraw: "No breakthrough today.", onDrawOffer: "Accepted.", onDrawDecline: "Not yet.",
    },
  },
  {
    id: "super-gm-takeshi",
    name: "Super GM Takeshi",
    avatar: "🏯",
    rating: 2720,
    difficulty: "master",
    personality: "precise",
    playstyle: "universal",
    openings: ["ruy-lopez", "english", "queens-gambit", "caro-kann"],
    accuracy: 0.97, blunderRate: 0.0015, inaccuracyRate: 0.02, bookDepth: 22,
    country: "Japan", countryFlag: "🇯🇵",
    style: "Super-GM precision", bio: "Top 50 in the world — relentlessly accurate.",
    drawAcceptThreshold: 80, resignThreshold: 600,
    taunts: {
      greeting: "Good luck. You'll need it 🏯", onCheck: "Exact check.", onCapture: "Precisely.",
      onBlunder: "Unusual.", onWin: "Inevitable.", onLose: "Outstanding game.",
      onDraw: "Both flawless.", onDrawOffer: "Accepted.", onDrawDecline: "Microscopic edge.",
    },
  },
  {
    id: "legend-leoni",
    name: "Legend Leoni",
    avatar: "💎",
    rating: 2800,
    difficulty: "master",
    personality: "legendary",
    playstyle: "universal",
    openings: ["ruy-lopez", "queens-gambit", "english", "sicilian", "caro-kann"],
    accuracy: 0.98, blunderRate: 0.001, inaccuracyRate: 0.015, bookDepth: 24,
    country: "Norway", countryFlag: "🇳🇴",
    style: "World-elite play", bio: "World #1 caliber. Errors are practically myth.",
    drawAcceptThreshold: 90, resignThreshold: 500,
    taunts: {
      greeting: "An honor to play 💎", onCheck: "Decisive check.", onCapture: "All foreseen.",
      onBlunder: "Once in a thousand games.", onWin: "Game of inevitability 💎", onLose: "A historic win for you.",
      onDraw: "Perfect on both sides.", onDrawOffer: "Accepted.", onDrawDecline: "Faint chances remain.",
    },
  },
];

const DEFAULT_BOT_IDS: Record<Difficulty, string> = {
  beginner: "rookie-rosa",
  intermediate: "tactic-tanvi",
  advanced: "counter-kira",
  expert: "endgame-eito",
  master: "gm-nova",
};

export function getBotByDifficulty(difficulty: Difficulty): BotProfile[] {
  return BOT_PROFILES.filter((bot) => bot.difficulty === difficulty);
}

export function getBotById(id: string): BotProfile | undefined {
  return BOT_PROFILES.find((bot) => bot.id === id);
}

export function getDefaultBot(difficulty: Difficulty): BotProfile {
  const preferredBot = getBotById(DEFAULT_BOT_IDS[difficulty]);
  if (preferredBot) return preferredBot;

  const difficultyBots = getBotByDifficulty(difficulty);
  if (difficultyBots.length > 0) return difficultyBots[0];

  return BOT_PROFILES[0];
}

export function getRandomBot(difficulty: Difficulty): BotProfile {
  const bots = getBotByDifficulty(difficulty);
  if (bots.length === 0) return getDefaultBot("beginner");
  return bots[Math.floor(Math.random() * bots.length)] ?? getDefaultBot(difficulty);
}
