// Per-course library of named variations (after the trunk).
// For lessons without a title-keyword match, we pick a variation by lesson index.

export const COURSE_VARIATIONS = {
  "kings-indian": [
    { name: "Mar del Plata Main Line", moves: [["d5", "7.d5 — Locking the center, both sides will attack on opposite wings."], ["Nbd7", "7...Nbd7 — Preparing ...Nh5 and ...f5."], ["O-O", "8.O-O Nh5 9.Re1 — Modern theory."]] },
    { name: "Bayonet Attack", moves: [["d5", "7.d5 Nbd7 8.b4 — White's queenside steamroller."], ["Nbd7", "7...Nbd7"], ["b4", "8.b4 — The Bayonet! White rushes the queenside."]] },
    { name: "Petrosian System", moves: [["d5", "7.d5 a5 8.Bg5 — Petrosian's positional approach."], ["a5", "7...a5 — Restraining b4."], ["Bg5", "8.Bg5 — Pinning the f6 knight."]] },
    { name: "Exchange Variation", moves: [["dxe5", "7.dxe5 dxe5 8.Qxd8 — Trading queens leads to a deceptively complex endgame."], ["dxe5", "7...dxe5"], ["Qxd8", "8.Qxd8 Rxd8 9.Bg5 — Endgame structure."]] },
    { name: "Sämisch Variation", moves: [["f3", "5.f3 — Sämisch! White builds a granite center supporting e4."], ["O-O", "5...O-O 6.Be3 e5 — Black still strikes the center."]] },
    { name: "Four Pawns Attack", moves: [["f4", "5.f4 — The Four Pawns Attack! Massive central space but vulnerable squares."], ["O-O", "5...O-O 6.Nf3 c5 — Counterattacking the overextended center."]] },
    { name: "Fianchetto Variation", moves: [["g3", "5.g3 — Quiet fianchetto setup."], ["O-O", "5...O-O 6.Bg2 Nbd7 — Solid Yugoslav setup."]] },
    { name: "Averbakh Variation", moves: [["Bg5", "6.Bg5!? — The Averbakh System! Pin first, develop later."], ["c5", "6...c5 — Counterstrike against d4."]] },
    { name: "Modern Main Line", moves: [["d5", "7.d5 Nbd7 8.O-O Nh5 9.g3 — Modern flexible setup."]] },
    { name: "Saemisch with O-O-O", moves: [["f3", "5.f3 O-O 6.Be3 e5 7.d5 — White prepares O-O-O and h-file storm."]] },
    { name: "Flexible System", moves: [["Nf3", "5.Nf3 O-O 6.h3 — Modern h3 setup avoiding ...Bg4."]] },
    { name: "Smyslov System", moves: [["g3", "5.g3 d6 6.Bg2 Nbd7 — Smyslov's flexible plan."]] },
    { name: "Gligorić Variation", moves: [["Be2", "6.Be2 e5 7.Be3 — Gligorić's positional approach."]] },
    { name: "Anti-KID with h3", moves: [["h3", "6.h3!? — A modern try, preventing ...Ng4 ideas."]] },
    { name: "Old Main Line", moves: [["d5", "7.d5 Nbd7 8.Bg5 — The classical retreat plan."]] },
    { name: "Endgame Structure", moves: [["dxe5", "7.dxe5 dxe5 8.Qxd8 Rxd8 9.Nxe5 — Tactical endgame trick!"]] },
    { name: "Anti-Mar del Plata", moves: [["Nd2", "8.Nd2 — Rerouting the knight to support b4."]] },
  ],
  "caro-kann": [
    { name: "Classical Variation", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Bf5 — The Classical, Capablanca's choice."], ["dxe4", "3...dxe4"], ["Nxe4", "4.Nxe4"], ["Bf5", "4...Bf5 — The bishop comes out before being locked in."]] },
    { name: "Advance Variation", moves: [["e5", "3.e5 — The Advance! White grabs space."], ["Bf5", "3...Bf5 — Same trick: bishop out first."], ["Nf3", "4.Nf3 e6 5.Be2 — Short Variation, modern main line."]] },
    { name: "Exchange Variation", moves: [["exd5", "3.exd5 — The Exchange. White trades to play against the IQP."], ["cxd5", "3...cxd5 4.Bd3 Nc6 5.c3 — Solid setup."]] },
    { name: "Panov-Botvinnik", moves: [["exd5", "3.exd5 cxd5 4.c4 — The Panov-Botvinnik Attack!"], ["cxd5", "3...cxd5"], ["c4", "4.c4 Nf6 5.Nc3 — Sharp IQP play."]] },
    { name: "Two Knights Attack", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Bf5 5.Ng3 — Forcing the bishop back."]] },
    { name: "Bayonet Attack", moves: [["e5", "3.e5 Bf5 4.h4 — The Bayonet! Aggressive kingside expansion."], ["Bf5", "3...Bf5"], ["h4", "4.h4 h6 5.g4 Bd7 — Sharp lines."]] },
    { name: "Short Variation Deep", moves: [["e5", "3.e5 Bf5 4.Nf3 e6 5.Be2 c5 — The Short Variation main line."]] },
    { name: "Modern Variation", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Nd7 — The Modern (Karpov) Variation."]] },
    { name: "Tartakower Variation", moves: [["e5", "3.e5 Bf5 4.Nc3 — The Tartakower Variation."]] },
    { name: "Gurgenidze System", moves: [["Nc3", "3.Nc3 g6 — The unusual Gurgenidze! Black plays a Pirc-like setup."]] },
    { name: "Fantasy Variation", moves: [["f3", "3.f3!? — The Fantasy/Maróczy Variation. White prepares e5 with extra support."]] },
    { name: "Steinitz Variation", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Nf6 5.Nxf6+ exf6 — The Bronstein-Larsen capture."]] },
    { name: "Korchnoi Variation", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Nf6 5.Nxf6+ gxf6 — Korchnoi's pawn structure."]] },
    { name: "Nimzowitsch Variation", moves: [["e5", "3.e5 c5!? — The Nimzowitsch Variation."]] },
    { name: "King's Indian Attack vs Caro", moves: [["d3", "3.d3 — The King's Indian Attack approach."]] },
    { name: "Endgame Variation", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Bf5 5.Ng3 Bg6 6.h4 — Heading to a structural endgame."]] },
    { name: "Hillarp-Persson Attack", moves: [["e5", "3.e5 Bf5 4.h4 h5 — The Hillarp-Persson plan."]] },
    { name: "Caro Move Order", moves: [["Nc3", "3.Nc3 — The traditional move order."]] },
    { name: "Apocalypse Attack", moves: [["Nf3", "3.Nf3 dxe4 4.Ng5!? — The Apocalypse Attack."]] },
    { name: "Goldman Variation", moves: [["Nc3", "3.Nc3 dxe4 4.Nxe4 Nf6 5.Qd3 — Goldman's idea."]] },
    { name: "Hector System", moves: [["e5", "3.e5 c5 4.dxc5 — Hector's pawn sac line."]] },
    { name: "Meeting Anti-Caro Lines", moves: [["c4", "2.c4 — The Anti-Caro c4 system."]] },
    { name: "Caro vs d4 Move Order", moves: [["c4", "Caro vs 1.d4: 1.d4 d5 2.c4 c6 — The Slav, a Caro cousin."]] },
  ],
  "london-system": [
    { name: "Classical London", moves: [["c3", "5.c3 c5 6.Nbd2 Nc6 — The classical London triangle."]] },
    { name: "Bd3 Setup", moves: [["Bd3", "4.Bd3 c5 5.c3 — Eyeing h7."]] },
    { name: "London with Nbd2", moves: [["Nbd2", "4.Nbd2 c5 5.c3 Nc6 — Modern flexible setup."]] },
    { name: "Aggressive London (Ne5)", moves: [["Nbd2", "4.Nbd2 5.Ne5 — Preparing the Ne5 outpost."]] },
    { name: "London vs King's Indian", moves: [["Bf4", "London vs KID setup: 1.d4 Nf6 2.Bf4 g6 3.e3 Bg7"]] },
    { name: "London vs Slav", moves: [["c3", "London vs ...c6: 1.d4 d5 2.Bf4 c6 3.e3 — Solid clamp."]] },
    { name: "London vs Queen's Gambit Dec.", moves: [["e3", "Against ...e6: 1.d4 d5 2.Bf4 e6 3.e3 Nf6 4.Nf3 c5"]] },
    { name: "Jobava London", moves: [["Nc3", "Jobava: 2.Nc3 Nf6 3.Bf4 — Sharp aggressive London!"]] },
    { name: "London vs Indian Defenses", moves: [["Bf4", "Against ...Nf6: 1.d4 Nf6 2.Bf4 d6 3.Nf3 — Anti-Indian London."]] },
    { name: "London Triangle Setup", moves: [["c3", "Triangle: pawns on c3, d4, e3 — the London skeleton."]] },
    { name: "London with Long Castle", moves: [["Qd2", "Long castling London: Qd2, O-O-O — Aggressive plan!"]] },
    { name: "London Endgame Patterns", moves: [["c3", "Quiet endgame plans arise from London structures."]] },
    { name: "London Move Orders", moves: [["Bf4", "Various move orders all reach the same London tabiya."]] },
    { name: "London Theory", moves: [["c3", "Modern London theory: deep but accessible."]] },
    { name: "London vs Symmetry", moves: [["c3", "Against symmetric ...Bd6: trade or play around it."]] },
    { name: "London Repertoire", moves: [["c3", "Build a complete London repertoire vs all defenses."]] },
    { name: "London Practical Tips", moves: [["c3", "Key London ideas: Bd3, Ne5, Qf3-h3 attack."]] },
    { name: "London Quick Setup", moves: [["c3", "5.c3 — Always c3 to secure d4 and prepare Bd3."]] },
    { name: "London Strategic Plans", moves: [["c3", "Strategic plans: kingside attack, central play, or queenside expansion."]] },
    { name: "London vs Reversed Setups", moves: [["c3", "When Black plays a reversed London — adapt with c3 and Nbd2."]] },
    { name: "London Common Mistakes", moves: [["c3", "Avoid moving the bishop too early — the Bf4 must be supported."]] },
    { name: "London Modern Treatment", moves: [["c3", "Carlsen-style London: flexible and deeply prepared."]] },
    { name: "London vs Anti-London", moves: [["c3", "Against ...c5 too early: 5.c3 to maintain d4."]] },
    { name: "London Pawn Structures", moves: [["c3", "Key pawn structures: Stonewall reversed, IQP, Carlsbad."]] },
    { name: "London Game Examples", moves: [["c3", "Study Carlsen, Kamsky, and Eljanov's London games."]] },
  ],
  "english-opening": [
    { name: "Reversed Sicilian", moves: [["Bg2", "5.Bg2 — The Reversed Dragon! White plays as Black does in the Sicilian Dragon."]] },
    { name: "Symmetrical English", moves: [["Bg2", "Symmetric: 1.c4 c5 2.Nc3 Nc6 3.g3 g6 4.Bg2 Bg7 — Mirror image!"]] },
    { name: "Botvinnik System", moves: [["e4", "Botvinnik: 1.c4 e5 2.Nc3 Nc6 3.g3 g6 4.Bg2 Bg7 5.e4 — Both sides in fianchetto with central pawns."]] },
    { name: "Hedgehog Defense", moves: [["e6", "Hedgehog: ...e6, ...b6, ...Bb7, ...d6 — Black coiled to strike."]] },
    { name: "Anti-King's Indian", moves: [["Nc3", "vs KID: 1.c4 Nf6 2.Nc3 g6 3.e4 — Avoiding mainline KID."]] },
    { name: "Mikenas-Carls Variation", moves: [["e4", "Mikenas: 1.c4 Nf6 2.Nc3 e6 3.e4 — The aggressive Mikenas-Carls!"]] },
    { name: "Anglo-Indian Defense", moves: [["Nf6", "Anglo-Indian: 1.c4 Nf6 — Black avoids committing pawns."]] },
    { name: "Anglo-Slav Defense", moves: [["c6", "Anglo-Slav: 1.c4 c6 — Black aims for ...d5."]] },
    { name: "Four Knights English", moves: [["Nf6", "Four Knights: 1.c4 e5 2.Nc3 Nc6 3.Nf3 Nf6 — Symmetric development."]] },
    { name: "Closed English", moves: [["g3", "Closed English: 1.c4 e5 2.Nc3 Nc6 3.g3 g6 — Slow strategic battle."]] },
    { name: "Open Catalan via English", moves: [["d4", "Transposing: 1.c4 e6 2.Nc3 d5 3.d4 — Catalan-like positions."]] },
    { name: "King's English", moves: [["e5", "King's English: 1.c4 e5 — Classical reversed Sicilian."]] },
    { name: "Anti-Slav with English", moves: [["c4", "Avoiding the Slav with English move order tricks."]] },
    { name: "English vs Dutch", moves: [["c4", "English vs ...f5: 1.c4 f5 — Independent lines."]] },
    { name: "English vs Modern", moves: [["c4", "vs ...g6: 1.c4 g6 2.Nc3 Bg7 — Anti-Modern setup."]] },
    { name: "English Endgames", moves: [["c4", "Typical English endgames feature queenside majorities."]] },
    { name: "English Pawn Structures", moves: [["c4", "Key structures: hedgehog, Maróczy bind, Carlsbad."]] },
    { name: "English Strategic Plans", moves: [["c4", "Plans: queenside expansion (b4-b5), central play (d4), kingside attack (h4-h5)."]] },
    { name: "English Move Orders", moves: [["c4", "Master English transpositions to QGD, KID, Slav."]] },
    { name: "English Theory Update", moves: [["c4", "Modern theory has revived ancient English lines."]] },
    { name: "English Practical Play", moves: [["c4", "Practical advice: keep flexibility, develop naturally."]] },
    { name: "English Repertoire", moves: [["c4", "Build a complete English repertoire vs all Black setups."]] },
    { name: "English Game Models", moves: [["c4", "Study Botvinnik, Karpov, Kramnik English games."]] },
    { name: "English vs Anti-English", moves: [["c4", "Anti-English with ...e5 — meet with g3 setups."]] },
    { name: "English Tactical Patterns", moves: [["c4", "Tactical patterns: discovered attacks, knight jumps to d5/c6."]] },
  ],
  "scandinavian-defense": [
    { name: "Main Line ...Qa5", moves: [["d4", "4.d4 Nf6 5.Nf3 c6 — Main Line, queen on a5."]] },
    { name: "Modern ...Nf6", moves: [["d4", "Modern: 2...Nf6 3.d4 Nxd5 — Avoiding queen exposure."]] },
    { name: "Portuguese Variation", moves: [["d4", "Portuguese: 2...Nf6 3.d4 Bg4!? — Sharp gambit line."]] },
    { name: "Icelandic Gambit", moves: [["c4", "Icelandic: 2...Nf6 3.c4 e6!? — Sacrificing a pawn for development."]] },
    { name: "...Qd6 Tiviakov", moves: [["Qd6", "3...Qd6 — The Tiviakov System! Queen sidesteps to d6."]] },
    { name: "...Qd8 Conservative", moves: [["Qd8", "3...Qd8 — The conservative retreat. Solid but passive."]] },
    { name: "Scandinavian Move Orders", moves: [["d5", "Various move orders into the Scandinavian."]] },
    { name: "Anti-Scandinavian", moves: [["d3", "White's Anti-Scandinavian: 2.d3 — Refusing to capture."]] },
    { name: "Scandinavian Endgames", moves: [["d4", "Endgames feature Black's queenside majority potential."]] },
    { name: "Modern Main Line", moves: [["d4", "4.d4 Nf6 5.Nf3 Bg4 6.h3 — Modern theory."]] },
    { name: "Marshall Variation", moves: [["d4", "Marshall: 4.d4 Nf6 5.Bd3 — Aggressive setup."]] },
    { name: "Mieses Variation", moves: [["d4", "Mieses: 4.d4 Nf6 5.Nf3 Bf5 — Active piece play."]] },
    { name: "Lasker Variation", moves: [["d4", "Lasker: ...Bg4 setup — Pinning the knight."]] },
    { name: "Pytel Variation", moves: [["d4", "Pytel: ...Qd6 with queenside castling ideas."]] },
    { name: "Bronstein Variation", moves: [["d4", "Bronstein's interpretation of the Scandinavian."]] },
    { name: "Anderssen Variation", moves: [["d4", "Anderssen's old line: ...Qa5 with ...e5 break."]] },
    { name: "...e5 Counterattack", moves: [["d4", "After 4.d4: ...e5 — Aggressive central counterstrike!"]] },
    { name: "Quick Development", moves: [["d4", "Black develops with ...Nf6, ...Bf5/g4, ...e6, ...Nbd7"]] },
    { name: "Fianchetto Setup", moves: [["d4", "Black plays ...g6, ...Bg7 in some lines."]] },
    { name: "Scandinavian Pawn Structures", moves: [["d4", "Key structure: Black has c6+d5 (later) similar to Caro."]] },
    { name: "Scandinavian Strategic Plans", moves: [["d4", "Plans: queenside castling, central pressure, queen rerouting."]] },
    { name: "Scandinavian vs Anti-lines", moves: [["d4", "Meeting White's tries to avoid main lines."]] },
    { name: "Scandinavian Tactics", moves: [["d4", "Tactical motifs: queen traps, ...e5 breaks, ...Bb4 pins."]] },
    { name: "Scandinavian Repertoire", moves: [["d4", "Build a complete Scandinavian repertoire."]] },
    { name: "Scandinavian Game Models", moves: [["d4", "Study Tiviakov, Bauer, and Sergei Tiviakov's games."]] },
    { name: "Scandinavian Modern Theory", moves: [["d4", "Modern theory respects the Scandinavian as fully sound."]] },
  ],
  "dutch-defense": [
    { name: "Leningrad Dutch", moves: [["g6", "Leningrad: ...g6, ...Bg7 — KID-like setup with ...f5."]] },
    { name: "Stonewall Dutch", moves: [["d5", "Stonewall: ...e6, ...d5, ...c6, ...Bd6 — Locked structure!"]] },
    { name: "Classical Dutch", moves: [["d6", "Classical: ...e6, ...Be7, ...d6 — Flexible play."]] },
    { name: "Staunton Gambit", moves: [["e4", "Staunton Gambit: 2.e4!? — White sacs a pawn for development."]] },
    { name: "Anti-Dutch 2.Bg5", moves: [["Bg5", "Anti-Dutch: 2.Bg5 — Trying to provoke ...h6 weaknesses."]] },
    { name: "Anti-Dutch 2.Nc3", moves: [["Nc3", "Anti-Dutch: 2.Nc3 — Aggressive Anti-Dutch."]] },
    { name: "Dutch vs c4", moves: [["g3", "vs c4: 1.d4 f5 2.c4 Nf6 3.g3 — Standard Dutch theory."]] },
    { name: "Leningrad Main Line", moves: [["g6", "Leningrad ML: 2.g3 Nf6 3.Bg2 g6 4.Nf3 Bg7 5.O-O O-O 6.c4 d6 7.Nc3"]] },
    { name: "Stonewall Main Line", moves: [["d5", "Stonewall ML: ...e6, ...d5, ...c6, ...Bd6, ...Nbd7, ...O-O"]] },
    { name: "Dutch Endgame Patterns", moves: [["g3", "Dutch endgames feature Black's space on the kingside."]] },
    { name: "Dutch Strategic Plans", moves: [["g3", "Plans: kingside attack with ...g5, central control, queenside play."]] },
    { name: "Dutch Move Orders", moves: [["g3", "Various move orders to reach Dutch positions."]] },
    { name: "Dutch vs Anti-lines", moves: [["g3", "Meeting White's tries to avoid main Dutch theory."]] },
    { name: "Dutch Practical Play", moves: [["g3", "Practical advice: don't fear ...f5 weaknesses, play actively."]] },
    { name: "Dutch Tactical Patterns", moves: [["g3", "Tactical patterns: ...e5, ...g5, queen lifts to h5."]] },
    { name: "Dutch Repertoire", moves: [["g3", "Build a complete Dutch repertoire vs all White setups."]] },
    { name: "Dutch Game Models", moves: [["g3", "Study Larsen, Nakamura, Williams Dutch games."]] },
    { name: "Dutch Pawn Structures", moves: [["g3", "Key structures: Leningrad chain, Stonewall locked center, Classical."]] },
    { name: "Dutch Defensive Resources", moves: [["g3", "Defensive resources when White attacks the kingside weaknesses."]] },
    { name: "Dutch Modern Theory", moves: [["g3", "Modern theory keeps the Dutch fully playable at all levels."]] },
    { name: "Dutch Quick Knockouts", moves: [["g3", "Common traps White falls into vs the Dutch."]] },
    { name: "Dutch Critical Lines", moves: [["g3", "Critical theoretical lines you must know."]] },
    { name: "Dutch Move-Order Tricks", moves: [["g3", "Move-order tricks to avoid Anti-Dutch lines."]] },
    { name: "Dutch Counterattacks", moves: [["g3", "Counterattacking ideas in the Dutch middlegame."]] },
    { name: "Dutch vs King's Indian Attack", moves: [["g3", "Dutch vs KIA setups."]] },
  ],
  "sicilian-deep-dive": [
    { name: "Najdorf English Attack", moves: [["Be3", "6.Be3 e6 7.f3 b5 8.Qd2 — English Attack: f3, Qd2, O-O-O, h-pawn storm."]] },
    { name: "Najdorf Bg5", moves: [["Bg5", "6.Bg5 — The Main Line. Pinning, threatening Bxf6."]] },
    { name: "Najdorf Be2 Classical", moves: [["Be2", "6.Be2 e5 — The Classical Najdorf."]] },
    { name: "Poisoned Pawn", moves: [["Bg5", "6.Bg5 e6 7.f4 Qb6!? — The Poisoned Pawn! Black grabs b2."]] },
    { name: "Najdorf Bc4 Fischer-Sozin", moves: [["Bc4", "6.Bc4 — The Fischer-Sozin Attack!"]] },
    { name: "Najdorf 6.h3 Adams", moves: [["h3", "6.h3 — Modern Adams Attack."]] },
    { name: "Najdorf 6.Be3 Modern", moves: [["Be3", "6.Be3 e5 — Modern Najdorf with ...e5."]] },
    { name: "Najdorf 6.f3", moves: [["f3", "6.f3 — Direct preparation for the English Attack."]] },
    { name: "Najdorf 6.g3", moves: [["g3", "6.g3 — Quiet fianchetto setup."]] },
    { name: "Najdorf 6.Rg1", moves: [["Rg1", "6.Rg1 — The fashionable Topalov idea, preparing g4."]] },
    { name: "Najdorf 6.Qf3", moves: [["Qf3", "6.Qf3 — The hypermodern queen development."]] },
    { name: "Sveshnikov Sicilian", moves: [["Nc6", "Sveshnikov: 5...Nc6 6.Ndb5 d6 7.Bf4 e5 8.Bg5 — Sharp main line."]] },
    { name: "Taimanov Sicilian", moves: [["Nc6", "Taimanov: 4...Nc6 5.Nc3 Qc7 — Flexible setup."]] },
    { name: "Kan Variation", moves: [["a6", "Kan: 4...a6 — Flexible move order avoiding theory."]] },
    { name: "Dragon Yugoslav Attack", moves: [["Be3", "Dragon: 6.Be3 g6 7.f3 Bg7 8.Qd2 — Yugoslav Attack!"]] },
    { name: "Accelerated Dragon", moves: [["Nc6", "Accelerated Dragon: ...Nc6 + ...g6 — Avoiding Yugoslav."]] },
    { name: "Scheveningen Sicilian", moves: [["Be2", "Scheveningen: ...e6 + ...d6 — Small Center setup."]] },
    { name: "Najdorf Endgames", moves: [["Be2", "Najdorf endgames are surprisingly common — know them!"]] },
    { name: "Najdorf vs Anti-Sicilian", moves: [["a6", "Najdorf players' guide to meeting Anti-Sicilians."]] },
    { name: "Najdorf Pawn Structures", moves: [["Be2", "Key structures: Boleslavsky hole on d5, Maróczy bind."]] },
    { name: "Najdorf Strategic Plans", moves: [["Be2", "Plans: ...b5-b4, ...d5 break, kingside counterplay."]] },
    { name: "Najdorf Tactical Patterns", moves: [["Be2", "Tactical patterns: ...d5! breaks, ...Nxe4 sacs, ...Bb7 attacks."]] },
    { name: "Najdorf Game Models", moves: [["Be2", "Study Fischer, Kasparov, Carlsen Najdorf games."]] },
    { name: "Najdorf Modern Theory", moves: [["Be2", "Modern computer-checked Najdorf theory."]] },
  ],
  "nimzo-indian": [
    { name: "Rubinstein 4.e3", moves: [["e3", "4.e3 — Rubinstein. Solid and flexible."]] },
    { name: "Classical 4.Qc2", moves: [["Qc2", "4.Qc2 — Classical Nimzo, avoiding doubled pawns."]] },
    { name: "Sämisch 4.a3", moves: [["a3", "4.a3 Bxc3+ 5.bxc3 — Sämisch: doubled pawns for the bishop pair."]] },
    { name: "Leningrad 4.Bg5", moves: [["Bg5", "4.Bg5 — Leningrad! Pinning the f6 knight."]] },
    { name: "Reshevsky System", moves: [["Nf3", "4.Nf3 — Reshevsky's flexible move order."]] },
    { name: "Hübner System", moves: [["e3", "4.e3 c5 5.Bd3 Nc6 6.Nf3 Bxc3+ — Hübner!"]] },
    { name: "Saemisch Modern", moves: [["a3", "4.a3 Bxc3+ 5.bxc3 d5 — Modern Sämisch theory."]] },
    { name: "Classical Main Line", moves: [["Qc2", "4.Qc2 O-O 5.a3 Bxc3+ 6.Qxc3 — Classical main line."]] },
    { name: "Rubinstein Main Line", moves: [["e3", "4.e3 O-O 5.Bd3 d5 6.Nf3 c5 — Rubinstein main line."]] },
    { name: "Bronstein Variation", moves: [["e3", "4.e3 O-O 5.Bd3 c5 6.Nf3 d5 — Bronstein move order."]] },
    { name: "Nimzo with ...d5", moves: [["e3", "Black's ...d5 setup — Classical strategy."]] },
    { name: "Nimzo with ...c5", moves: [["e3", "Black's ...c5 setup — Hypermodern strategy."]] },
    { name: "Nimzo with ...b6", moves: [["e3", "Black's ...b6 setup — Fianchetto strategy."]] },
    { name: "Nimzo Endgame Patterns", moves: [["Qc2", "Endgame patterns favor the side without doubled pawns."]] },
    { name: "Nimzo Pawn Structures", moves: [["e3", "Key structures: doubled c-pawns, IQP, hanging pawns."]] },
    { name: "Nimzo Strategic Plans", moves: [["e3", "Plans: targeting doubled pawns, central control, kingside attack."]] },
    { name: "Nimzo Tactical Patterns", moves: [["e3", "Tactical patterns: ...Bxc3 trades, ...Ne4 jumps, ...d5 breaks."]] },
    { name: "Nimzo Move Orders", moves: [["d4", "Move orders: ensure 3.Nc3 to invite the Nimzo."]] },
    { name: "Nimzo vs Anti-Nimzo", moves: [["d4", "Anti-Nimzo: 3.Nf3 (Queen's Indian) or 3.g3."]] },
    { name: "Nimzo Game Models", moves: [["d4", "Study Botvinnik, Karpov, Kramnik Nimzo games."]] },
    { name: "Nimzo Modern Theory", moves: [["d4", "Modern Nimzo theory remains rich and dynamic."]] },
    { name: "Nimzo Critical Lines", moves: [["d4", "Critical theoretical lines you must know."]] },
    { name: "Nimzo Repertoire", moves: [["d4", "Build a complete Nimzo-Indian repertoire."]] },
  ],
};
