/**
 * Build a single source of truth of fully-validated SAN sequences for every
 * masterclass lesson. Uses chess.js to walk the practiceLine and recover from
 * desync between `moves` (player) and `autoResponses` (opponent) by trying
 * either queue when the expected one is illegal. Writes the result to
 * src/lib/masterclass-validated-lines.ts as a Record<lessonId, string[]>.
 */
import { Chess } from "chess.js";
import { COURSES } from "../src/lib/courses-data";
import { MASTERCLASS_PRACTICE_EXTRAS } from "../src/lib/masterclass-practice-extras";
import * as fs from "fs";

const MC_COURSES = [
  "masterkurs-jobava-london",
  "masterkurs-kalashnikov",
  "masterkurs-kid",
  "masterkurs-queens-gambit",
  "masterkurs-ruy-lopez",
  "masterkurs-caro-kann",
  "masterkurs-najdorf",
];

interface Built { sans: string[]; startFen?: string; truncatedAt?: number; sourceLen: number; }

// Map of known startFen → SAN prefix played from the initial position.
// This lets every masterclass variation start from move 1 (like Jobava London)
// rather than mid-position, so users always see the full game build-up.
const STARTFEN_PREFIX: Record<string, string[]> = {
  "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1": ["e4"],
  "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1": ["d4"],
  "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2": ["e4", "e5"],
};

function buildLesson(lesson: any): Built | null {
  const pl = (lesson.practiceLine && (lesson.practiceLine.moves?.length || lesson.practiceLine.autoResponses?.length))
    ? lesson.practiceLine
    : MASTERCLASS_PRACTICE_EXTRAS[lesson.id];
  if (!pl) return null;

  // If we know how to reach pl.startFen from the initial position, replay the
  // prefix moves from move 1 so the line starts at the very beginning.
  const knownPrefix = pl.startFen ? STARTFEN_PREFIX[pl.startFen] : null;
  const startFromInitial = !pl.startFen || !!knownPrefix;

  let firstSide: "w" | "b" = "w";
  if (!startFromInitial && pl.startFen && pl.startFen.split(" ")[1] === "b") firstSide = "b";
  // After replaying the known prefix, side-to-move is whatever pl.startFen said.
  if (startFromInitial && pl.startFen && pl.startFen.split(" ")[1] === "b") firstSide = "b";
  const playerFirst = firstSide === pl.playerColor;

  const game = (() => {
    try {
      if (startFromInitial) {
        const g = new Chess();
        for (const san of (knownPrefix ?? [])) g.move(san);
        return g;
      }
      return pl.startFen ? new Chess(pl.startFen) : new Chess();
    } catch { return new Chess(); }
  })();
  const out: string[] = startFromInitial ? [...(knownPrefix ?? [])] : [];
  let pi = 0, ai = 0, turn = playerFirst;
  const sourceLen = (pl.moves?.length ?? 0) + (pl.autoResponses?.length ?? 0);

  const tryQueue = (q: "p" | "a"): boolean => {
    if (q === "p" && pi < pl.moves.length) {
      try { if (game.move(pl.moves[pi].move)) { out.push(pl.moves[pi].move); pi++; return true; } } catch { /* */ }
    } else if (q === "a" && ai < pl.autoResponses.length) {
      try { if (game.move(pl.autoResponses[ai])) { out.push(pl.autoResponses[ai]); ai++; return true; } } catch { /* */ }
    }
    return false;
  };

  let truncatedAt: number | undefined;
  for (let i = 0; i < sourceLen; i++) {
    const primary = turn ? "p" : "a";
    const fallback = turn ? "a" : "p";
    let ok = tryQueue(primary);
    if (!ok) ok = tryQueue(fallback);
    if (!ok) {
      // skip an illegal head; if both queues are stuck, stop.
      const beforeP = pi, beforeA = ai;
      if (primary === "p" && pi < pl.moves.length) pi++;
      else if (primary === "a" && ai < pl.autoResponses.length) ai++;
      else if (pi < pl.moves.length) pi++;
      else if (ai < pl.autoResponses.length) ai++;
      else { truncatedAt = out.length; break; }
      // If the fallback didn't progress and both queues are now empty heads of illegal moves
      if (pi === beforeP && ai === beforeA) { truncatedAt = out.length; break; }
    }
    turn = !turn;
  }
  return { sans: out, startFen: startFromInitial ? undefined : pl.startFen, truncatedAt, sourceLen };
}

const result: Record<string, { sans: string[]; startFen?: string }> = {};
const report: string[] = [];

for (const cid of MC_COURSES) {
  const c = COURSES.find(x => x.id === cid)!;
  let truncCount = 0, totalLessons = 0, totalPliesIn = 0, totalPliesOut = 0;
  for (const l of c.lessons) {
    const b = buildLesson(l);
    if (!b) continue;
    totalLessons++;
    totalPliesIn += b.sourceLen;
    totalPliesOut += b.sans.length;
    if (b.truncatedAt !== undefined) truncCount++;
    result[l.id] = { sans: b.sans, ...(b.startFen ? { startFen: b.startFen } : {}) };
  }
  report.push(`${cid}: lessons=${totalLessons} truncated=${truncCount} sourcePlies=${totalPliesIn} validatedPlies=${totalPliesOut}`);
}

const banner = `/**
 * AUTO-GENERATED by scripts/build-masterclass-validated.ts.
 * For each masterclass lesson, the full chess.js-validated SAN sequence
 * (interleaved player + opponent moves), starting from \`startFen\` if any,
 * else from the initial position. Use as the single source of truth on the
 * interactive trainer board so every variation plays cleanly start-to-end.
 *
 * Build report:
${report.map(r => " *   - " + r).join("\n")}
 *
 * Re-generate after editing courses-data.ts or masterclass-practice-extras.ts:
 *   bunx tsx scripts/build-masterclass-validated.ts
 */
export interface ValidatedLine { sans: string[]; startFen?: string; }
export const MASTERCLASS_VALIDATED_LINES: Record<string, ValidatedLine> = ${JSON.stringify(result, null, 2)};
`;

fs.writeFileSync("src/lib/masterclass-validated-lines.ts", banner);
console.log("Wrote src/lib/masterclass-validated-lines.ts");
console.log(report.join("\n"));
