INSERT INTO public.blog_posts (slug, title, excerpt, body_md, tags, status, published_at, reading_minutes) VALUES
('how-to-beat-london-system-as-black',
 'How to Beat the London System as Black',
 'A practical repertoire against the London System for club players — three reliable answers and the key middlegame plans.',
 E'# How to Beat the London System as Black\n\nThe London System is one of the most popular openings at club level because it is solid and easy to learn for White. The bad news for London players: Black has at least three reliable, low-theory ways to play for a win.\n\n## 1. The ...c5 / ...Qb6 plan\n\nAfter `1.d4 d5 2.Bf4 Nf6 3.e3 c5 4.c3 Qb6` Black immediately targets b2 and the dark-square weaknesses that the London bishop leaves behind.\n\n## 2. The King''s Indian setup\n\nIf you already play the King''s Indian, just play it. `1.d4 Nf6 2.Bf4 g6 3.Nf3 Bg7 4.e3 d6 5.h3 O-O` — Black follows up with `...Nbd7`, `...e5` and a classic kingside attack.\n\n## 3. The ...Bf5 mirror\n\nMirror White''s setup: `1.d4 d5 2.Bf4 Bf5`. The bishop pair is balanced and Black gets equal play with zero memorization.\n\n## Key middlegame ideas\n\n- Trade the dark-squared bishops if you can.\n- Look for the `...Nh5` move to exchange the Bf4.\n- Don''t fear `...c5` even when it lets White recapture with the pawn.\n\n## Practice this opening\n\nPlay it against our 1600-rated bot at [/play](/play) — five games against the same position will teach you more than any video.\n',
 ARRAY['openings', 'black-repertoire', 'london-system'], 'published', now(), 4),
('5-caro-kann-traps-under-1500-elo',
 '5 Caro-Kann Traps Every Player Under 1500 Should Know',
 'Five concrete tactics in the Caro-Kann that win material or the game outright against unprepared opponents.',
 E'# 5 Caro-Kann Traps Every Player Under 1500 Should Know\n\nThe Caro-Kann (1.e4 c6) is famous for being solid, but it also hides several practical traps that score very well below 1500.\n\n## Trap 1 — Fantasy gone wrong\n`1.e4 c6 2.d4 d5 3.f3?! dxe4 4.fxe4 e5!` — Black blasts the center open.\n\n## Trap 2 — Advance variation Bf5 trick\n`1.e4 c6 2.d4 d5 3.e5 Bf5 4.Nc3?! e6 5.g4 Bg6 6.Nge2 c5!`\n\n## Trap 3 — Exchange variation premature Bd3\n`1.e4 c6 2.d4 d5 3.exd5 cxd5 4.Bd3 Nc6 5.c3 Nf6 6.Bf4 Bg4! 7.Qb3 Qd7` — White cannot defend b7 and develop comfortably.\n\n## Trap 4 — Two Knights overextension\n`1.e4 c6 2.Nf3 d5 3.Nc3 Bg4 4.h3 Bxf3 5.Qxf3 Nf6 6.d3 e6 7.g3?! Bb4!`\n\n## Trap 5 — Classical recapture\n`1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Bf5 ... 11.Bf4 Qa5+!`\n\n## Drill these positions\nLoad each into our trainer at [/openings](/openings).\n',
 ARRAY['openings', 'caro-kann', 'tactics'], 'published', now(), 4),
('best-chess-openings-for-beginners-2026',
 'Best Chess Openings for Beginners in 2026',
 'A tested list of beginner-friendly openings for White and Black that emphasize understanding over memorization.',
 E'# Best Chess Openings for Beginners in 2026\n\nIf you''re under 1200, you don''t need theory — you need openings that teach principles.\n\n## For White\n### Italian Game (1.e4 e5 2.Nf3 Nc6 3.Bc4)\nClassic and principled. Forces you to think about the f7 square.\n\n### London System (1.d4 d5 2.Bf4)\nIf you hate memorizing lines, this is your opening.\n\n## For Black\n### Caro-Kann (1...c6 vs e4)\nSolid and low-risk.\n\n### King''s Indian Defense (vs d4)\nLet White have the center, then crush it from the flank.\n\n### Scandinavian (1.e4 d5)\nGreat surprise weapon.\n\n## What matters more than the opening\nPiece activity, king safety, and not blundering pieces. Try our [/puzzles](/puzzles) page.\n',
 ARRAY['openings', 'beginners', 'study-plan'], 'published', now(), 3),
('how-to-improve-from-1000-to-1500-elo',
 'How to Improve from 1000 to 1500 Elo (Real Plan)',
 'A four-month study plan with concrete daily habits to reach 1500 rating without spending a dollar.',
 E'# How to Improve from 1000 to 1500 Elo (Real Plan)\n\n## Month 1 — Tactics only\n- 20 puzzles per day, every day.\n- Focus on forks, pins, skewers, discovered attacks.\n- Play 1–2 long games per day (10+5 or longer). No bullet.\n\n## Month 2 — Endgames\n- King and pawn vs king: master the opposition.\n- Lucena and Philidor rook endgames.\n\n## Month 3 — One opening per color\n- Italian for White, Caro-Kann for Black. Learn 8 moves and the plans, not 25 moves of theory.\n\n## Month 4 — Game review\n- After every loss, identify the move where the evaluation flipped.\n- Write down the lesson in one sentence.\n\nUse our manual [game review](/games) — no AI assist, just your own analysis.\n',
 ARRAY['improvement', 'study-plan', 'rating'], 'published', now(), 4),
('common-chess-mistakes-beginners-make',
 '7 Common Chess Mistakes Beginners Make (and How to Stop)',
 'The seven habits that keep you stuck below 1200 — and the specific drills that fix each one.',
 E'# 7 Common Chess Mistakes Beginners Make\n\n## 1. Moving the same piece twice in the opening\nDevelop all your pieces before moving any one piece twice.\n\n## 2. Bringing the queen out too early\nThe queen gets chased by minor pieces.\n\n## 3. Ignoring the center\nControl e4, d4, e5, d5.\n\n## 4. Castling too late\nCastle by move 10 in 90% of games.\n\n## 5. Trading without a plan\nEvery trade should improve your position.\n\n## 6. Hope chess\nAssume your opponent''s best move and plan around it.\n\n## 7. Playing too fast\nUnder 1500, slow down. Use your clock.\n\nFix these with our [/training](/training) drills.\n',
 ARRAY['beginners', 'mistakes', 'improvement'], 'published', now(), 3),
('how-to-play-the-sicilian-defense',
 'How to Play the Sicilian Defense as Black',
 'A complete starter guide to the Sicilian Defense — pick a variation, learn the plans, win games.',
 E'# How to Play the Sicilian Defense as Black\n\n## The Najdorf (5...a6) — Most flexible, most theory.\n## The Dragon (5...g6) — Sharp, attacking.\n## The Kan (4...a6) — Low-theory, flexible.\n## The Taimanov (4...Nc6) — Flexible piece development.\n## The Accelerated Dragon (4...g6) — Avoids the Yugoslav Attack.\n\n## Universal tips\n- The c5 pawn opens the c-file for your rook.\n- The ...d6 / ...e6 / ...e5 break is the soul of the Sicilian.\n- Avoid trading queens early.\n\nLearn the moves on our [opening explorer](/openings).\n',
 ARRAY['openings', 'sicilian', 'black-repertoire'], 'published', now(), 4),
('how-to-read-chess-notation',
 'How to Read Chess Notation in 5 Minutes',
 'Algebraic chess notation explained simply, with examples — so you can finally read chess books and online games.',
 E'# How to Read Chess Notation in 5 Minutes\n\n## The board\n- Files (columns) a–h.\n- Ranks (rows) 1–8.\n\n## Piece letters\nK=King, Q=Queen, R=Rook, B=Bishop, N=Knight, no letter=Pawn.\n\n## Move format\n- `e4` = pawn moves to e4.\n- `Nf3` = knight moves to f3.\n- `Bxd5` = bishop captures on d5.\n- `O-O` = kingside castle.\n- `+` = check, `#` = checkmate.\n\n## Example\n`1.e4 e5 2.Nf3 Nc6 3.Bb5` = the Ruy Lopez.\n\nReplay any of your games at [/games](/games).\n',
 ARRAY['rules', 'beginners', 'notation'], 'published', now(), 2),
('chess-endgame-principles-every-player-should-know',
 'Chess Endgame Principles Every Player Should Know',
 'The five endgame rules that decide most club games — opposition, active king, passed pawns, and more.',
 E'# Chess Endgame Principles Every Player Should Know\n\n## 1. The king is a fighting piece — march it to the center.\n## 2. Opposition — when kings face each other one square apart, the side NOT to move has the opposition.\n## 3. Passed pawns must be pushed.\n## 4. Rook activity beats material.\n## 5. The principle of two weaknesses — create a second one on the other side.\n\nPlay endgame puzzles at [/puzzles](/puzzles).\n',
 ARRAY['endgames', 'principles', 'improvement'], 'published', now(), 3),
('how-much-time-should-i-spend-on-chess',
 'How Much Time Should I Spend on Chess Per Day?',
 'A realistic time-budget for adult improvers — and what to do with each minute.',
 E'# How Much Time Should I Spend on Chess Per Day?\n\n30 focused minutes beats 3 unfocused hours.\n\n## The 30-minute plan\n- 10 min tactical puzzles\n- 10 min one long game\n- 10 min review the game\n\n## What NOT to do\n- Don''t grind bullet for hours.\n- Don''t watch streams instead of playing.\n- Don''t bounce between openings every week.\n\nStart your daily streak at [/training](/training).\n',
 ARRAY['study-plan', 'improvement', 'time-management'], 'published', now(), 3),
('chess-clock-time-controls-explained',
 'Chess Clock Time Controls Explained — Bullet, Blitz, Rapid, Classical',
 'What every time control means, how increment works, and which one is best for your skill level.',
 E'# Chess Clock Time Controls Explained\n\n## Bullet (1–2 min) — Fast, bad for learning until you''re 1600+.\n## Blitz (3–5 min) — Most popular online format.\n## Rapid (10–30 min) — Best for improvement.\n## Classical (30+ min) — Tournament time controls.\n\n## Increment vs delay\n- Increment (+2): you gain 2 seconds after every move.\n- Delay (d5): the clock pauses 5 seconds before counting.\n\n## Best by skill\n- Under 1000: 15+10\n- 1000–1500: 10+5\n- 1500–2000: 10+5 and 30+0\n- 2000+: whatever you enjoy\n\nPick yours at [/play](/play).\n',
 ARRAY['rules', 'time-controls', 'beginners'], 'published', now(), 3),
('chess-pattern-recognition-how-to-train',
 'Pattern Recognition: The Real Skill That Wins Chess Games',
 'Why memorizing patterns matters more than calculation — and the three drills that build it fastest.',
 E'# Pattern Recognition: The Real Skill That Wins Chess Games\n\n## 1. Mate-in-1 sprint\nDo 50 mate-in-1 puzzles in a row.\n\n## 2. Tactical motifs by theme\n20 forks, then 20 pins, then 20 skewers.\n\n## 3. Replay master games at speed\nClick through classical games at one move per second.\n\n## How long until it works\n30 minutes a day for 60 days = visible rating gain.\n\nStart at [/puzzles](/puzzles).\n',
 ARRAY['improvement', 'patterns', 'tactics'], 'published', now(), 3),
('why-i-built-masterchess',
 'Why I Built MasterChess (Built by a Kid)',
 'The story of a 13-year-old building the chess platform he wanted to use — no ads, no clutter, just chess.',
 E'# Why I Built MasterChess\n\nHi, I''m Nikola. I''m 13 and I built MasterChess because I couldn''t find a chess site that wasn''t covered in ads and pop-ups.\n\n## What''s different\n- No ads. Ever.\n- No "premium" gates.\n- No fake players.\n- No engine assistance in human games.\n\n## What''s here\n- 9 bot opponents from 400 to 2000 ELO\n- Online matchmaking\n- A daily puzzle\n- Lessons in my own voice\n- Tournaments, clans, and a battle pass\n\nStart playing at [/play](/play).\n',
 ARRAY['about', 'story', 'product'], 'published', now(), 2)
ON CONFLICT (slug) DO NOTHING;